### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by nicosabena** [auth0/auth0.net#110]
I now I'm a little late to the discussion on design (https://github.com/auth0/auth0.net/issues/45), but shouldn't async methods be named "xxxAsync()" if there is ever any hope of adding sync versions?
Even if sync versions are not in the roadmap any time soon, the conventions in .Net state that async methods should have the "Async" suffix. HttpClient, for example, an async only class, has all of its methods utilizing the prefix (https://msdn.microsoft.com/en-us/library/system.net.http.httpclient%28v=vs.118%29.aspx).

**Comment by jerriep** [comment]
@nicosabena 

You are correct and we are addressing this soon. For now there is no plans to add sync methods, but we will fix the ...Async() naming convention by adding new methods using that convention and marking the existing ones as obsolete.
