### ISSUE TITLE
target .net 4?

### ISSUE THREAD

**Issue by TerribleDev** [auth0/auth0.net#115]
Think you can have a target of .net 4?

**Comment by jerriep** [comment]
We will look into .NET 4 support, but it would probably not be forthcoming
soon

**Comment by jerriep** [comment]
@TerribleDev I will be closing this issue for now. There are no plans currently to support .NET 4 or earlier

**Comment by TerribleDev** [comment]
@jerriep that is fair, if we go to the trouble to re-write parts of the api so they can support 4.x would our PR be welcomed?

**Comment by jerriep** [comment]
It can certainly be considered as long as it does not add long term maintenance burden. Can you give me a brief overview of your thinking around this, i.e. which parts it is you want to rewrite and how you want to go about it?

**Comment by TerribleDev** [comment]
Sure, I'll look over the code next week and get back to you.
