### ISSUE TITLE
Incorrect target

### ISSUE THREAD

**Issue by JonCanning** [auth0/auth0.net#116]
I'm having a problem installing this library using Paket, please see this issue here:

https://github.com/fsprojects/Paket/issues/1645

It looks like the target is incorrect, could you confirm?

**Comment by monkieboy** [comment]
Please fix the target it is incorrect, this issue is outstanding for 3 months, will literally take 3 minutes to fix.

**Comment by jerriep** [comment]
@JonCanning @monkieboy Gentlemen. my apologies for this. I have updated and pushed new versions to NuGet

**Comment by monkieboy** [comment]
@jerriep Thank you very much :)
