### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by dcworldwide** [auth0/auth0.net#122]
Will this work as is on .net core?

**Comment by jerriep** [comment]
We do not have a version which target .NET Standard yet, but you can use the existing PCL.

Please refer to this sample:
https://github.com/auth0-samples/auth0-aspnetcore-sample/tree/master/03-Login-Custom

Just be sure to import the correct PCL framework, as per the sample:
https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/master/03-Login-Custom/SampleMvcApp/project.json#L34-L41

**Comment by jerriep** [comment]
@dcworldwide New version which targets .NET Standard 1.1 is available on NuGet
