### ISSUE TITLE
Serching for users using the GetAllAsync method does not filter on ConnectionName

### ISSUE THREAD

**Issue by tillmaurer** [auth0/auth0.net#124]
When making a query like below, I get users from all connections. Should the returned list not be filtered by connection since connection name is included as a parameter?

`var users = await _apiClient.Users.GetAllAsync(null, null, null, null, _connectionName,null,null,query,"v2");`

**Comment by jerriep** [comment]
@tillmaurer As per the Management API Docs (https://auth0.com/docs/api/management/v2#!/Users/get_users)

> Only applies when using search_engine=v1. To filter by connection with search_engine=v2, use q=identities.connection:"connection_name"

So either do this:
```
var users = await _apiClient.Users.GetAllAsync(null, null, null, null, _connectionName,null,null,query,"v1");
```

or 

```
string query = "identities.connection:\"Your Connection Name Here\"";
var users = await _apiClient.Users.GetAllAsync(null, null, null, null, null,null,null,query,"v2");
```

**Comment by kientv** [comment]
I'm using this command, but connection not working, it's still return sms connection user.   
`curl -H "Authorization: Bearer {token}" https://oneid-playaround-dev.au.auth0.com/api/v2/users?connection=q=identities.connection.raw:"connection1"&q=+84983082333&search_engine=v3`
