### ISSUE TITLE
IApiConnection instance can't be replaced in AuthenticationApiClient

### ISSUE THREAD

**Issue by IlSocio** [auth0/auth0.net#125]
I'd like to replace the IApiConnection instance with my own implementation, but it doesn't seems to be possible, because the AuthenticationApiClient doesn't provide a constructor overload that takes the IApiConnection.
https://github.com/auth0/auth0.net/blob/netstandard/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs

Basically, I need to configure the httpclient to use a proxy.
Marco.

**Comment by jerriep** [comment]
Thanks for reporting this @IlSocio 

I am looking into solving this for you

**Comment by IlSocio** [comment]
Thank you @jerriep  👍

**Comment by jerriep** [comment]
@IlSocio I added overloads to the constructors of `AuthenticationApiClient` and `ManagementApiClient` which allows you to pass in an `HttpMessageHandler`

You can for example do the following

```
var handler = new HttpClientHandler
{
    Proxy = new WebProxy("http://localhost:8888")
};
var api = new AuthenticationApiClient("jerrie.auth0.com", handler);

var tokenInfo = await api.GetTokenInfoAsync("some jwt");
```

Please grab V3.5 from NuGet

**Comment by IlSocio** [comment]
Thank you! @jerriep that's perfect :)
