### ISSUE TITLE
AuthenticationParameters on PasswordlessEmailRequest should be of type object

### ISSUE THREAD

**Issue by gregsdennis** [auth0/auth0.net#129]
I cannot add any parameters (like a redirect URL) to a request as the `AuthenticationParameters` property is a `string`.  It should be an `object` so that it serializes to a JSON object like the API is expecting.

There are no tests which cover this.

As a workaround, I'm manually calling the API without the `AuthenticationClient`.

**Comment by jerriep** [comment]
@gregsdennis Can you please give me a sample code snippet which demonstrates your problem? Also explain to me what SDK is sending to the API and what you are expecting it to send?

**Comment by nicosabena** [comment]
@jerriep when putting some string in `AuthenticationParameters`, like a serialized JSON or a query string, the API responds this:

`ApiException: error in authParams - invalid type: string (expected object)`

The API expects a payload like this:

```json
{
  "client_id":"ZnbrrKD9Xje0JEKyrqiPffOGC3GT2Ou3", 
  "connection":"email|sms", 
  "email":"EMAIL", 
  "phone_number":"PHONE_NUMBER", 
  "authParams": {
    "response_type": "code",
    "state" : "....",
    "nonce": "....",
    "scope": "openid",
    "redirect_uri" : "...."
  }
}
```

As you see, `authParams`  should be serialized as object.

This works as a workaround:

```c#
   public static class AuthenticationClientExtensions
    {
        public static Task<PasswordlessEmailResponse> StartPasswordlessEmailFlowAsync2(this AuthenticationApiClient client, PasswordlessEmailRequest2 request)
        {
            return client.Connection.PostAsync<PasswordlessEmailResponse>("passwordless/start",
                            new
                            {
                                client_id = request.ClientId,
                                connection = "email",
                                email = request.Email,
                                send = request.Type.ToString().ToLower(),
                                authParams = request.AuthenticationParameters
                            },
                            null, null, null, null, null);
        }
    }

    public class PasswordlessEmailRequest2 : PasswordlessEmailRequest
    {
        public new object AuthenticationParameters { get; set; }
    }
```

So you can do this:

```c#
   var lockContext = HttpContext.GenerateLockContext(this._options.Value);
    var authenticationClient = new Auth0.AuthenticationApi.AuthenticationApiClient(this._auth0Settings.Value.Domain);

    var authParams = new {
                            scope= "openid",
                            response_type="code",
                            redirect_uri = this._auth0Settings.Value.CallbackUrl,
                            nonce = lockContext.Nonce ,
                            state = lockContext.State 
                            };

    await authenticationClient.StartPasswordlessEmailFlowAsync2(
        new PasswordlessEmailRequest2()
            {
                ClientId = this._auth0Settings.Value.ClientId,
                Email = email,
                Type = PasswordlessEmailRequestType.Link,
                AuthenticationParameters = authParams
        });```

**Comment by alastairs** [comment]
I've been looking at this today to see if it can be quickly fixed given the required change is quite trivial. However, trying to add tests around this behaviour is proving very difficult as I can't figure out how to run them. Looking at the way the tests are architected suggests that it's going to be very difficult to get the tests to run and pass on my machine: for example, I am missing the required `client-secrets.json` configuration file.

**Comment by nicosabena** [comment]
PR https://github.com/auth0/auth0.net/pull/132. We need to decide if we do a major version or not for this.

**Comment by jerriep** [comment]
@gregsdennis Find V3.7 on NuGet which fixes this issue

Thanks @nicosabena for the fix :)
