### ISSUE TITLE
ExchangeCodeForAccessTokenAsync gives missing device parameter error

### ISSUE THREAD

**Issue by tvand7093** [auth0/auth0.net#130]
### Problem Description
I recently was migrating your old auth0.net nuget package to the latest package when I started to run into device parameter issues. We originally had our code using refresh tokens without fail 100% of the time. However, the move seems to have brought this new issue to the surface.

We currently have implemented this in an MVC application.  I am able to login with the lock widget just fine using the "offline_access" scope. But once it gets to the point where I need to call `ExchangeCodeForAccessTokenAsync`, it errors out saying that the device parameter must be specified. Now I have even tried to specify the device parameter on the lock widget, which works but it still seems to error around 25% of the time.

I have included the code that I am essentially trying to use. I'm not sure if this is an issue the `AuthenticationApiClient` or what. It may be that I migrated stuff wrong, but based on your documentation, and the fact it was working prior to the upgrade, this should work.

Any insights would be greatly appreciated as I have bashed my head against the wall with this one!. 

### System
 - ASP.NET MVC 5.2.3
 - Lock Widget Version 10.4
 - Auth0.AuthenticationApi Version 3.6.0

### Lock widget code

```javascript
var options = {
    languageDictionary: {
        emailInputPlaceholder: "user@user.com",
        title: "My System"
    },
    auth: {
        redirectUrl: 'https://myurl.com/LoginCallback.ashx',
        params: {
            scope: 'openid offline_access',
            device: "My device id"
        },
        responseType: 'code',
        responseMode: 'form_post'
    }
};

var lock = new Auth0Lock(
    '@System.Configuration.ConfigurationManager.AppSettings["Auth0:ClientId"]',
    '@System.Configuration.ConfigurationManager.AppSettings["Auth0:Domain"]',
    options);

lock.show();
```

### LoginCallback.ashx

```csharp
var api = new AuthenticationApiClient(new Uri($"https://{Domain}"));
var exchange = new ExchangeCodeRequest()
{
    ClientSecret = ClientSecret,
    ClientId = ClientId,
    AuthorizationCode = context.Request.Params["code"],
    RedirectUri = context.Request.Url.ToString()
};

// this line fails with the device id error.
var token = await api.ExchangeCodeForAccessTokenAsync(exchange);
```

**Comment by jerriep** [comment]
@tvand7093 

First off apologies for my late reply.

I am not able to reproduce your problem.

A couple of questions though:

1. Why are you requesting `offline_access` for a web application? Offline access is only for native applications
2. The code you included above is a deviation from what is installed by the NuGet package. Is there a reason you decided to go with `responseMode: 'form_post'`?
3. You seem to be using MVC 5.x. If you are using OWIN you should actually try and use the OWIN middleware. See this Quickstart: https://auth0.com/docs/quickstart/webapp/aspnet-owin

**Comment by tvand7093** [comment]
No problem, thanks for looking into it.

I know that the `offline_access` is normally not for web apps, but we try (maybe incorrectly) to keep a 'rolling' login. Essentially the users don't want to click anything when they open up the app for the first time of the day, like GitHub works. 

The only reason `responseMode` is `form_post` is that I tried to upgrade the Lock version to try and resolve this issue (we were using 9.1 I think before). I only left `form_post` because  I didn't want to have to refactor and re-test everything in the authentication bits to see if it would work. We are extremely busy during the last half of the year and usually can only focus on bug fixes, and try to avoid large refactors as stability is extremely important. 

Finally, we have been using Auth0 in the application since day one ~2.5 years ago. We installed the original MVC tooling and Auth0 Nuget which used the non-OWIN version of login. 

I have somewhat expected this to be related to the offline access usage being incorrect, but the annoying thing is that this **WAS** working just fine before moving to the new Auth0.AuthenticationApi Nuget.

 Is there a more appropriate workflow for a GitHub like experience with login? Everything I have seen just says to set the token expiration to be longer, but that still would require login after expiration as I understand it. I would love to remove the refresh token bit if there is a better way to support this use case.

In the meantime though, I will investigate the OWIN setup and see how tricky that will be to migrate.

**Comment by jerriep** [comment]
@tvand7093  In an ASP.NET application it is not the token received from Auth0 which determines the session lifetime, but the cookie. So in the `LoginCallback.ashx.cs` file you will notice there is a call to `FederatedAuthentication.SessionAuthenticationModule.CreateSessionCookie()`

By default this cookie is set only for the duration of the session, so once the user closes the browser window, their session will expire:

![image](https://cloud.githubusercontent.com/assets/1006420/21166642/4c256d02-c1d9-11e6-81a3-3c1b170f6e84.png)

What you need to do is to change to call to `FederatedAuthentication.SessionAuthenticationModule.CreateSessionCookie()` to make it persistent and also to specify the lifetime of the cookie. 

So in your `LoginCallback.ashx.cs` file change the call to:

```
FederatedAuthentication.SessionAuthenticationModule.CreateSessionCookie(user, persistent: true, sessionCookieLifetime: TimeSpan.FromDays(7));
```

That makes the cookie persistent for a duration of 7 days:

![image](https://cloud.githubusercontent.com/assets/1006420/21166672/93d191f8-c1d9-11e6-8794-0b2a179b6aa4.png)

If you do not specify the duration it will be persistent forever, and I do not think you should do that, so choose a duration which makes sense - typically 7 to 14 days.

Hope this helps

**Comment by tvand7093** [comment]
Ahhh, makes sense. I was unaware of the extra options in the `CreateSessionCookie`. Thanks for the help!
