### ISSUE TITLE
Exception when using Auth0.Authentication API on net46

### ISSUE THREAD

**Issue by jpozo20** [auth0/auth0.net#139]
When using the Authentication API on .NET 4.6.x, whenever Auth0 does a web request it's throwing an exception :

System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0

I believe it's related to this issue on corefx: https://github.com/aspnet/JavaScriptServices/issues/487

As it says at the end of the thread it can be solved by upgrading the binding redirect on System.Net.Http to version 4.3.1

**Comment by jerriep** [comment]
@jpozo20 A couple of things:

1. Can you please provide me with a small code snippet which demonstrates your problem?

2. Which version of the NuGet package are you using?

**Comment by jpozo20** [comment]
I'm using the v3.7.0 nuget
And here is a simple git where I make the call to the authentication api:

https://gist.github.com/jpozo20/9e983c34bb5df382e09c708a5e54d085

The request fails on the _apiClient.AuthenticateAsync(authenticationRequest); call with the exception said above.

**Comment by jerriep** [comment]
@jpozo20 I will look into this for you

In the meantime, can you perhaps check out the V4 pre-release on NuGet and see whether that works for you?

**Comment by jpozo20** [comment]
@jerriep It's it documented? Sometime ago I read a guide about using it since it has many breaking changes, but I didn't understand much. Is there a migration guide?

**Comment by jerriep** [comment]
@jpozo20 Yes, here is the migration guide:
http://auth0.github.io/auth0.net/migrating.html

**Comment by jerriep** [comment]
BTW, here is sample code for how you would go about what you are trying to do with the 4.x libraries:

https://github.com/auth0-samples/auth0-aspnet-owin-mvc-sample/blob/oidc-conformant/02-Custom-Login/MvcApplication/MvcApplication/Controllers/AccountController.cs#L34-L80

**Comment by jpozo20** [comment]
Thanks, I'll give it a try.

**Comment by jpozo20** [comment]
Hello again, I had some problems getting past the authorization on net452, but it seems the problem persists on the v4 and net46 beta since you guys are still using an old version of System.Net.Http

**Comment by jerriep** [comment]
Hi @jpozo20 , I worked around this issue by explicitly installing V4.3.1 of System.Net.Http.

I will see to update our NuGet packages to ensure that this version gets pulled in, but I will need to do some extra testing across platforms to ensure nothing else breaks.

For now, please just go to your NuGet packages for your application, and ensure you install 4.3.1 of System.Net.Http manually.

Let me know if that sorts you out

**Comment by jpozo20** [comment]
My bad :sweat_smile:

I tried that before, and it didn't seem to work. I updated the package in all my projects and problem was persisting but it looks like my main project didn't have the System.Net.Http v4.3.1
And now it is indeed working, the issue can be closed.
