### ISSUE TITLE
logout returnTo parameter is ignored

### ISSUE THREAD

**Issue by yaplex** [auth0/auth0.net#141]
I am trying to logout user and after logout redirect him back to homepage. I providing returnTo parameter but it is ignored, the user get redirected to the first URL in Allowed Logout URLs list.
(I am using Auth0-ASPNET-OWIN 2.0.0)

**Comment by jerriep** [comment]
Can you please show me some sample of the code you are using, so I can see how you are doing this?

**Comment by yaplex** [comment]
I am using Lock 10. The following is Logout method in controller:
`            var absoluteReturnUrl = string.IsNullOrEmpty(returnUrl)
                ? Url.Action("Index", "Home", new {}, Request.Url.Scheme)
                : Url.IsLocalUrl(returnUrl)
                    ? new Uri(Request.Url, returnUrl).AbsoluteUri
                    : returnUrl;

            var auth0Logout = string.Format("https://{0}/v2/logout?returnTo={1}",
                ConfigurationManager.AppSettings["auth0:Domain"],
                Url.Encode(absoluteReturnUrl));
            return Redirect(auth0Logout);
`
I checked under debugger and absoluteReturnUrl has a correct value, but when I verify it in network tab in Chrome I see logout url with clientId parameter, but without returnTo parameter. Looks like during Redirect(auth0Logout) your library somehow intercept that redirect and change URL (inserting clientId but removing returnTo) and probably that is the reason why later I get redirected to the first URL in the list of allowed logout URLs. 

All code was copied from your sample application, I did not do anything special.
Please let me know if you need more information.

**Comment by jerriep** [comment]
If you are using the Auth0-ASPNET-OWIN 2.0.0 library, then this is how you would do logout:

https://github.com/auth0-samples/auth0-aspnet-owin-mvc-sample/blob/oidc-conformant/01-Login/MvcApplication/MvcApplication/Controllers/AccountController.cs#L16-L23

Can you please try that?

**Comment by yaplex** [comment]
Yes, I saw that sample, but it does not work for me for some reasons. The code is executed, but nothing happens, I am not logged out, I get redirected back to home page, but I am authenticated.

**Comment by jerriep** [comment]
That means that your local cookie is not cleared. Which is strange, because that is what this line is doing:

```
HttpContext.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);
```

Is it possible you can send me the code for your application?

If not then please the code for your Login and Logout actions, as well as the code where you configure your OWIN middleware - in particular the Cookie and other authentication middleware

**Comment by yaplex** [comment]
[auth0.zip](https://github.com/auth0/auth0.net/files/934752/auth0.zip)
I attached files related to login. if you still have troubles to identify the issue, let me know, I will create a separate fully functional application to show issues with login.
  <package id="Auth0-ASPNET-Owin" version="2.0.0" targetFramework="net461" />

**Comment by jerriep** [comment]
OK, so in V2 of the OWIN middleware, we handle the logout for you, so you do not have to redirect to the Auth0 logout URL manually.

This causes the issue where you rightly noted that we "intercept" the call to logout.

Also, the name of the Cookie is different from what you declared in your Startup.cs file, vs what I used in the sample code above, and that's the reason that the cookie was apparently not cleared.

So for you code you can fix all of this by replacing the code for your `Signout` action in your `AccountController` class with the following code:

```
[Authorize]
public void Signout(string returnUrl = null)
{
    var absoluteReturnUrl = string.IsNullOrEmpty(returnUrl)
        ? Url.Action("Index", "Home", new { }, Request.Url.Scheme)
        : Url.IsLocalUrl(returnUrl)
            ? new Uri(Request.Url, returnUrl).AbsoluteUri
            : returnUrl;

    HttpContext.GetOwinContext().Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
    HttpContext.GetOwinContext().Authentication.SignOut(new AuthenticationProperties
    {
        RedirectUri = absoluteReturnUrl
    }, "Auth0");
}
```

This will clear the local cookie correctly, and also ensure that your return URL parameter gets passed to the Auth0 logout endpoint, so Auth0 will redirect to the correct URL afterwards.

Also, just ensure that the URL to the list of **Allowed Logout URLs** for your Client in the Auth0 dashboard

**Comment by jerriep** [comment]
@yaplex I am closing this issue. Feel free to open again if the solution above did not resolve your problem
