### ISSUE TITLE
Version 3 dox?

### ISSUE THREAD

**Issue by danieljsummers** [auth0/auth0.net#142]
The current documentation site is really nice, but it looks like the documentation is for the version 4 API.  I checked, but couldn't find any equivalent for the version 3 API.  I've done some looking in the source to help me get headed in the right direction, but is there a place where v3 is still documented?

**Comment by danieljsummers** [comment]
The site to which I'm referring is <http://auth0.github.io/auth0.net/index.html>.  _(Sorry for leaving that out of my initial submission.)_

**Comment by jerriep** [comment]
Daniel, we do not have any documentation currently for V 3.x of the SDK.

The SDK is still quite similar though, and the V4 documentation should steer you in the right direction.

Also, you can refer to the documentation of the actual Authentication API and Management API:

* https://auth0.com/docs/api/authentication
* https://auth0.com/docs/api/management/v2

**Comment by danieljsummers** [comment]
OK - I appreciate the information.  :)  Thanks!
