### ISSUE TITLE
Resource Owner Password - Audience missing in AuthenticationApiClient?

### ISSUE THREAD

**Issue by IlSocio** [auth0/auth0.net#143]
I'm trying to use the resource owner password grant: 
https://auth0.com/docs/api/authentication#resource-owner-password

But I need to set the Audience parameter and it seems to be missing in the AuthenticationApiClient (tried both v3 and v4)
https://github.com/auth0/auth0.net/blob/v4/src/Auth0.AuthenticationApi/Models/ResourceOwnerTokenRequest.cs

Is there any alternative way to set the Audience?

Thanks, 
Marco.

**Comment by jerriep** [comment]
Hi Marco. I'll get back to you on this one.

**Comment by jerriep** [comment]
@IlSocio Version 4.1.0 adds support for `Audience` parameter. Please update your NuGet package

**Comment by IlSocio** [comment]
Thank you jerriep, this is a great news! :)
