### ISSUE TITLE
GetTokenAsync with scope does not work

### ISSUE THREAD

**Issue by brcarey** [auth0/auth0.net#144]
If you look at the auth0 doco:

https://auth0.com/docs/api/authentication#authorization-code

there is no scope parameter of oauth/token endpoint, so you cannot get profile info back int he JWT.

Perhaps this:

https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs#L357

should be changed to use oauth/ro (which is what I am using Connection.PostAsync to hit)

**Comment by jerriep** [comment]
@brcarey You should use the Resource Owner Password grant flow:
https://auth0.com/docs/api/authentication#resource-owner-password

When using the Auth0.net client you can do the following:

```
var authenticationApiClient = new AuthenticationApiClient(new Uri(GetVariable("AUTH0_AUTHENTICATION_API_URL")));

// Act
var authenticationResponse = await authenticationApiClient.GetTokenAsync(new ResourceOwnerTokenRequest
{
    ClientId = "your client id",
    ClientSecret = "your client secret",
    Realm = "your connection name, e.g. Username-Password-Authentication",
    Scope = "openid profile", // Here you can set the scope
    Username = "user@sample.com",
    Password = "password"              
});
```

The `oauth/ro` endpoint will be deprecated at some point in the future, so it should not be used

**Comment by brcarey** [comment]
with the above request to oauth/token, there is no profile information
returned in the jwt, despite it being present in the scope

**Comment by jerriep** [comment]
@brcarey 

I will need to see the actual request and response

Please capture the network traffic for me with Fiddler. Look for the request to the `/oauth/token` endpoint, right click on it and select Save > Selected Sessions > As Text

Once you have saved the text file, please edit it to delete the value of your actual `client_secret` (because it is a secret ;) ), and then post that text file for me here, so I can have a look at it

**Comment by jerriep** [comment]
BTW, are you referring to the `access_token` or the `id_token`? 

The `access_token` will not contain user information - only the `id_token`

For more info see this:
https://auth0.com/blog/why-should-use-accesstokens-to-secure-an-api/

**Comment by brcarey** [comment]
Thanks, will do. I am referring to the id_token

**Comment by jerriep** [comment]
@brcarey Did you manage to sort this issue out?

**Comment by brcarey** [comment]
sorry for the late reply @jerriep, only as far as making the raw http request to oauth/token to find that the scope parameter has no impact on the token returned

![image](https://cloud.githubusercontent.com/assets/1684235/25827974/29429ba4-3491-11e7-8cd3-33cb9c4192f0.png)

that is not the same token that I receive from oauth/ro, which includes the profile information that I am after

**Comment by brcarey** [comment]
And in fact, the documentation for oauth/token does not even indicate you can pass username/password

https://auth0.com/docs/api/authentication#authorization-code

**Comment by jerriep** [comment]
You need to look at the Resource Owner Password flow docs:
https://auth0.com/docs/api/authentication#client-credentials

**Comment by jerriep** [comment]
Can you please post here the actual `id_token` being returned?

**Comment by brcarey** [comment]
for oauth/token or oauth/ro?

**Comment by brcarey** [comment]
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYnJlbmRhbkBjdXJyZW5jeXZ1ZS5jb20iLCJuaWNrbmFtZSI6ImJyZW5kYW4iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvNjk5NDhkYTE0N2E4MWFkZGJiYzJiNDNiYTJmMTZmMDQ_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZici5wbmciLCJ1cGRhdGVkX2F0IjoiMjAxNy0wNS0xMFQwMTo0ODoyNS41NjRaIiwiaXNzIjoiaHR0cHM6Ly9jdXJyZW5jeXZ1ZS5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NThmZDQwMDNhODIzOTEwODYxZTI3ZDkyIiwiYXVkIjoiMk94YXdhZUF1UjNSNW9WWUY1elZBbTF1QUFsOHQyS00iLCJleHAiOjE0OTU1ODA5MDUsImlhdCI6MTQ5NDM4MDkwNX0._T4APtew_3rVswVN0XaTgzSOc-RciDpgeqHzlmh1pO4

that is with 

> scope: openid profile

**Comment by jerriep** [comment]
OK, so if I view that token in jwt.io, I can see the user's profile claims (`name`, `nickname` and `picture`). So the requested `scope` is being honored.

Can you please explain what you are expecting? 

Maybe there is a miscommunication between us...

**Comment by brcarey** [comment]
I would like attributes of app_metadata to be returned, which is what we get with oauth/ro, is that possible?

**Comment by jerriep** [comment]
No and yes ;)

No - not in the same way as before. With the new OIDC-compliant pipeline we do not return `app_metadata`.
Yes - by doing a little extra work. See [this document](https://auth0.com/docs/scopes/preview) and in particular the Custom Claims section.

If you then request `scope: openid profile` you should get those new claims.

For a general background on OIDC Conformant clients, I also suggest reading these:
* https://auth0.com/docs/api-auth/tutorials/adoption
* https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

**Comment by brcarey** [comment]
Excellent, thanks.

So the namespace prefix for properties, that does not need to correspond with any value from the authentication request?

Great work with the SDK too by the way, its been great to work with.

**Comment by jerriep** [comment]
No, the namespace prefix can be whatever you choose. I would suggest using something which relates to your company or name though, e.g. `https://www.currencyvue.com/`

And thanks :)

**Comment by brcarey** [comment]
Working all good now, thanks for the help
