### ISSUE TITLE
Auth0 v4.x requires Newtonsoft.Json v10.0.2

### ISSUE THREAD

**Issue by IlSocio** [auth0/auth0.net#145]
I just updated Auth0 client to v4 and I noticed that it requires Newtonsoft.Json v10.0.2 
https://github.com/auth0/auth0.net/blob/master/nuget/Auth0.Core.nuspec#L56
I'm wondering... does Auth0 really needs some new features introduced in json v10 or it could also work with previous versions?

**Comment by jerriep** [comment]
We do not specifically need this.

Is it causing you problems?

**Comment by IlSocio** [comment]
I'm currently using v9 and this requirement causes a forced update of Newtonsoft.Json to v10 for the project where I'm using Auth0.
I'm afraid it could introduce a compatibility break because I'm using v9 in all other projects of the same solution.

**Comment by jerriep** [comment]
10.x mostly adds async support, and some other performance enhancements:
http://james.newtonking.com/archive/2017/03/21/json-net-10-0-release-1-async-performance-documentation-and-more

Can you see whether 10.x breaks anything for you. If it gives you real
problems, I can revert to 9.x on our side, but if not I would prefer
staying on 10.x

**Comment by IlSocio** [comment]
thanks for your promptly reply jerriep.
My project seem to be working fine on v10 and all the tests are passed, but I'm using many 3rd party components too, which I'm not able to fully test and those are dependent on json v9.
To avoid breaking change issues, I'll keep using the auth0 v4 prerelease... as soon as the 3rd party components will be updated to require json v10 I'll update auth0 to v4 final.

**Comment by jerriep** [comment]
Sure. If this causes you real issues let me know and I can relax the requirement
