### ISSUE TITLE
Query that works in the Dashboard doesn't work in Users.GetAllAsync 

### ISSUE THREAD

**Issue by Shrulik** [auth0/auth0.net#149]
This is on version 3.7 of Auth0.Net

This is what I tried in the Dashboard and it worked : 
email.raw:"someemailaddress@live.com"

Now, trying to recreate this in code, I have tried a query of type :

```C#
var email = "someemailaddress@live.com";

//These return 0 results
managementApiClient.Users.GetAllAsync(q: $"⁠⁠⁠⁠email﻿⁠⁠⁠⁠.raw:\"{email}\"",  searchEngine: "v2");
managementApiClient.Users.GetAllAsync(q: $"⁠⁠⁠⁠email﻿⁠⁠⁠⁠:\"{email}\"",  searchEngine: "v2");

//This one works, but it looks at all fields and might cause issues.
managementApiClient.Users.GetAllAsync(q: email,  searchEngine: "v2");
```
Just to elaborate further, the last query returns a user, and this user has a value in the Email field, and it is equal to "someemailaddress@live.com".

**Comment by jerriep** [comment]
@Shrulik 

I just tested the following with V4.x and it works fine:
```
string email = "you@email.com";
var searchResults = await apiClient.Users.GetAllAsync(q: $"email.raw: \"{email}\"", searchEngine: "v2");
```

The code for searching has not changed between version 3.x and 4.x, so it should work in 3.x

Could you perhaps trace the actual query being sent to Auth0 with something like Fiddler, and then pasting that request (and response) for me here so I can have a look at it?

**Comment by jerriep** [comment]
Closing issue due to non-response.

Feel free to open again if you get time to look at it, and the problem persists
