### ISSUE TITLE
Missing supported field in UserBase

### ISSUE THREAD

**Issue by arieradle** [auth0/auth0.net#152]
In src/Auth0.ManagementApi/Models/UserBase.cs there is no property which translates to
"verify_email" parameter, when making POST request to /api/v2/users, as described here: [Create user API](https://auth0.com/docs/api/management/v2#!/Users/post_users).

Please add the following property
` 
        [JsonProperty("verify_email")]
        public bool? VerifyEmail { get; set; }
`
in src/Auth0.ManagementApi/Models/UserBase.cs

**Comment by jerriep** [comment]
@arieradle 

I added a `VerifyEmail` property to `UserCreateRequest`

Please grab 4.4.0 from NuGet
https://www.nuget.org/packages/Auth0.ManagementApi/4.4.0

**Comment by arieradle** [comment]
I'm not sure we're OIDC-conformant.
Will v3.x Nugets have this change?

**Comment by jerriep** [comment]
Are you using the Management API or Authentication API packages?

**Comment by arieradle** [comment]
Both

**Comment by jerriep** [comment]
Can you check whether your clients are set to OIDC Conformant? If so, then just use V4.x

If not, well then I will have to retrofit this change to V3. Let me know

**Comment by arieradle** [comment]
"OIDC Conformant" switch is off for all clients

**Comment by jerriep** [comment]
I'll look into this...

**Comment by jerriep** [comment]
@arieradle 

OK, V3.8.0 is available: https://www.nuget.org/packages/Auth0.ManagementApi/3.8.0

**Comment by arieradle** [comment]
I've tested the Nuget - it didn't work.

Here's the request log form Auth0 console:

"body": {
    "client_id": "********",
    "tenant": "HHHHHH",
    "connection": "Testing-Database",
    "password": "*****",
    "given_name": "AAAAA",
    "family_name": "BBBBB",
    "email": "XXXXX",
    "email_verified": false
  },
  "query": {
    "method": "POST",
    "host": "login.auth0.com",
    "port": 443,
    "resource": "/lo/users/direct",
    "id": "********"
  }
}

There is no "verify_email" field.

**Comment by jerriep** [comment]
Can you show me your C# source code?

**Comment by arieradle** [comment]
```c#
var tokenRequest = new
            {
                grant_type = "client_credentials",
                client_id = managementClientId,
                client_secret = managementSecret,
                audience = $"https://{domain}/api/v2/"
            };

      var tokenResponse = $"https://{domain}/oauth/token"
                                        .PostJsonAsync(tokenRequest)
                                        .ReceiveJson().Result;
//...

 var managementClient = new ManagementApiClient((string)tokenResponse.access_token,
                    new System.Uri($"https://{domain}/api/v2"));

//...

auth0User = managementClient.Users.CreateAsync(new UserCreateRequest
                   {
                        Email = request.Email,
                        Password = request.Password,
                        FirstName = request.FirstName,
                        LastName = request.LastName,
                        Connection = connection,
                        EmailVerified = false,
                        VerifyEmail = false
                    }).Result;
```

**Comment by jerriep** [comment]
@arieradle I believe you are looking at the wrong log. You should look at the "API Operation" log entry. Here is an example from my side when I sent `VerifyEmail = false`:

```json
{
  "method": "post",
  "path": "/api/v2/users",
  "query": {},
  "userAgent": ".NET/PCL",
  "body": {
    "connection": "Username-Password-Authentication",
    "given_name": "Jerrie",
    "family_name": "Pelser",
    "verify_email": false,
    "email": "jerrie+1@jerriepelser.com",
    "email_verified": false
  },
  "channel": "api",
  "ip": "58.136.217.100",
  "auth": {
    "user": {},
    "strategy": "jwt",
    "credentials": {
      "scopes": [
        ...
      ]
    }
  }
}
```

In this case **no** verification email is sent out.

And when I set `VerifyEmail = true`:

```json
{
  "method": "post",
  "path": "/api/v2/users",
  "query": {},
  "userAgent": ".NET/PCL",
  "body": {
    "connection": "Username-Password-Authentication",
    "given_name": "Jerrie",
    "family_name": "Pelser",
    "verify_email": true,
    "email": "jerrie+1@jerriepelser.com",
    "email_verified": false
  },
  "channel": "api",
  "ip": "58.136.217.100",
  "auth": {
    "user": {},
    "strategy": "jwt",
    "credentials": {
      "scopes": [
        ...
      ]
    }
  }
}
```

In this case a verification email is indeed sent out.

The JSON from you log you posted above looks like it is from the log entry entitled "Success Signup". For this log entry you will not see a `verify_email` attribute, since that is not actually stored on the user object. 

Can you please check on your side again? 

Look at the "API Operation" log entry... also test by actually setting the `VerifyEmail` both false and true, and ensure that the correct behavior is happening.

I don't like giving you a "it works on my computer" answer, but in this case that is all I can offer you ;)

**Comment by arieradle** [comment]
OK, I've found the correct log.
And we're still getting the verification email.

```javascript
{
  "method": "post",
  "path": "/api/v2/users",
  "query": {},
  "userAgent": ".NET/PCL",
  "body": {
    "connection": "Testing-Database",
    "given_name": "dd",
    "family_name": "dd",
    "verify_email": false,
    "email": "...",
    "email_verified": false
  },
  "channel": "api",
  "ip": "...",
  "auth": {
    "user": {},
    "strategy": "jwt",
    "credentials": {
      "scopes": [
        "read:users",
        "update:users",
        "delete:users",
        "create:users",
        "create:users_app_metadata",
        "create:user_tickets",
        "read:user_idp_tokens"
      ]
    }
  }
}
```

**Comment by jerriep** [comment]
Wow, this is strange. I tested and definitely did not get the verification email when I set `VerifyEmail` to false.

Can you test doing this directly via the Management API Console (https://auth0.com/docs/api/management/v2) or with Postman (https://auth0.com/docs/api/postman) ?

**Comment by arieradle** [comment]
@jerriep I'll try reproducing with postman. Could it be that the "update" call, as mentioned above, issues the verification email?

**Comment by jerriep** [comment]
I'll ping on out internal channel to see whether anyone is aware of why this would happen - as this does not seem to be an actual issue with the .NET SDK...

Will let you know if I hear something back

**Comment by jerriep** [comment]
BTW, what "update" call are you referring to?

**Comment by arieradle** [comment]
We're blocking the user.

```javascript
{
  "method": "patch",
  "path": "/api/v2/users.....",
  "query": {},
  "userAgent": ".NET/PCL",
  "body": {
    "blocked": true
  },
  "channel": "api",
  "ip": "...",
  "auth": {
    "user": {},
    "strategy": "jwt",
    "credentials": {
      "scopes": [
        "read:users",
        "update:users",
        "delete:users",
        "create:users",
        "create:users_app_metadata",
        "create:user_tickets",
        "read:user_idp_tokens"
      ]
    }
  }
}
```

But the verification email is issued upon user creation, not the update. The issue is definitely with the backend.

**Comment by jerriep** [comment]
@arieradle What is your Auth0 tenant name ?

**Comment by arieradle** [comment]
@jerriep netformx

**Comment by jerriep** [comment]
BTW, I tested the same sequence as you - creating and then updating the user - and that did not trigger any email for me, so I do not think that is the case

**Comment by jerriep** [comment]
OK, one of the support people is looking into this. He will create a support ticket on your behalf, so you and him can communicate directly

**Comment by jerriep** [comment]
I will close this issue, as it is obviously not related to .NET anymore

**Comment by arieradle** [comment]
Great! Thanks.
