### ISSUE TITLE
New method GetUsersByEmailAsync throws error: Query validation error: Additional properties not allowed

### ISSUE THREAD

**Issue by FutureGUIs** [auth0/auth0.net#157]
Calling the new method GetUsersByEmailAsync with an email address is throwing this error: 

Query validation error: Additional properties not allowed

**Comment by jerriep** [comment]
@FutureGUIs 

My apologies. Please update to Auth0.Core 4.0.1. I have also published Auth0.ManagementApi 4.6.1 which takes a dependency on this particular version

**Comment by FutureGUIs** [comment]
Thanks, that works now.
