### ISSUE TITLE
Missing ttl_sec property in EmailVerificationTicketRequest and PasswordChangeTicketRequest 

### ISSUE THREAD

**Issue by foman** [auth0/auth0.net#161]

**Comment by jerriep** [comment]
Closed via #162

**Comment by jerriep** [comment]
@foman I pushed V4.9.0 to NuGet

Please note that I renamed your `ExpiresIn` property to `Ttl`. The reason being that many people look at the Management API docs, and then search for the corresponding property in the .NET SDK. `ExpiresIn` is very different, so I am afraid people would not easily make the connection, whereas `Ttl` matches well with the actual attribute required in the underlying API
