### ISSUE TITLE
Management API UsersClient is missing a method for getting a list of Guardian enrollments

### ISSUE THREAD

**Issue by jaccus** [auth0/auth0.net#163]
This method is available on the v2 management API here [https://auth0.com/docs/api/management/v2#!/Users/get_enrollments](https://auth0.com/docs/api/management/v2#!/Users/get_enrollments) but is missing on the latest version of auth0.net [(Auth0.ManagementApi 4.9.0](https://www.nuget.org/packages/Auth0.ManagementApi/)).

**Comment by ritdaw** [comment]
+1

**Comment by damieng** [comment]
Will track Guardian on #164
