### ISSUE TITLE
ApiConnection is not disposing of HttpClient properly, while requiring a dynamic token value in constructor

### ISSUE THREAD

**Issue by jaccus** [auth0/auth0.net#165]
Either let configure token dynamically, on method call (then can make the ApiConnection a singleton and keep it global), or properly dispose of it (since need to recreate clients as often as tokens expire, e.g., every few hours).

**Comment by jerriep** [comment]
@jaccus I assume you are referring to `ManagementApiClient`?

I can look into adding a `SetToken` method which will update the token on the underlying `ApiConnection`. Will that work for you?

**Comment by jaccus** [comment]
This goes back to me having to use Guardian features from the SDK. While the `Guardian` property was hidden on `ManagementApiClient` I started using `GuardianClient` directly, which in turn will cause memory leaks due to `ApiConnection` not disposing of `HttpClient`'s properly.

Since `ManagementApiClient` is using clients under the hood anyways, guess this issue does bubble up to `ManagementApiClient`.

**Comment by jerriep** [comment]
*Please* do not use `GuardianClient`. Your code will break when I update that API. 

Also, `HttpClient` should not be disposed. See https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed and https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by jaccus** [comment]
Yes it should not, but your current implementation (where you instantiate HttpClient inside of your ApiConnection) makes it necessary to update the token value.

**Comment by jaccus** [comment]
Another thing is, if you encapsulate an instantiation of an IDisposable object in your constructor, it's a good practice to implement IDisposable yourself (in this case IApiConnection), where in the Dispose method you dispose of HttpClient.

**Comment by yngndrw-sage** [comment]
The documentation page for this SDK suggests that the clients are not threadsafe and therefore shouldn't be shared:
http://auth0.github.io/auth0.net/#client-reuse-and-thread-safety

The issue with this is that there's no way to either clean-up or re-use the underlying ```HttpClient```. Maybe ```ApiConnection``` could be passed in to the API clients and token changing allowed ?

**Comment by jerriep** [comment]
@yngndrw-sage 

That is specifically related to when using the `GetLastApiInfo()` method which retrieves the status for the last API call. That particular "feature" has nothing to do with how we use or dispose of the `HttpClient` internally.

If you do not use that, then you can certainly use it in multi-threaded environments without issue.

**Comment by yngndrw-sage** [comment]
Thanks for clarifying @jerriep, that makes sense. I can then use a custom ```HttpClientHandler``` to allow the access token to be changed / refreshed as required.

**Comment by davidallyoung** [comment]
Hey guys, sorry I'm kicking tires on something that looks settled, but I wanted to ask about ensuring we're not going to run into socket exceptions if we can't control the lifetime of the HttpClient that is directly instantiated on every instantiation of the Client. I see that previously this was discussed, and that the client could be used as a singleton as long as you don't call a specific method `GetLastApiInfo()`. 

Could there be an overload that allows us to either:

A. Pass in an HttpClient that we maintain the lifetime of (singleton for all of our auth0 requests)
B. Pass in a ApiConnection that we maintain the lifetime of?

My concern at the moment is that we implement using the Client as a singleton and then someone uses it in a way that is not thread-safe (calls `GetLastApiInfo()`), or the implementation changes later making more parts of the Client not thread safe.

The auth0 client documentation says the ApiClients are lightweight and safe to instantiate, but that's not really true. Creating an instance per request and thus newing up new HttpClients could really cause issues. As per the MSDN documentation found here: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7 `HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.` we can see that this could really lead to some sad times at high load.

Let me know if there's movement we can make on this. We're also ok with implementing it ourselves, but I wanted to bring it up for discussion. Thank you!
