### ISSUE TITLE
GetActiveUsersAsync is deadlocking in ASP.NET context

### ISSUE THREAD

**Issue by chrisrobertsoncypress** [auth0/auth0.net#167]
When I call .Wait() or .Result() on this method, it appears to deadlock in my Visual Studio debugger. The issue may be that the pattern is different in this method - you are are awaiting a result without ConfigureAwait(false) like you do in the rest of the patterns. So it is awaiting on my ASP.NET synchronization context (possibly). I can get this method to work by surrounding it in a Task.Run().

var result = await Connection.GetAsync<object>("stats/active-users", null, null, null, null);
return Convert.ToInt64(result);

**Comment by jerriep** [comment]
Why are you calling `Wait()` or `Result()` and not using `async` and `await` ?

**Comment by chrisrobertsoncypress** [comment]
At some point in the future we probably will. We want to make them blocking for now until we have time to take a look at all of our code. Our code is MVC controllers using auto injected services which then call your code. I inherited a lot of code and I don't have time right now to make it all consistent. But that may be the right thing to do when I have time.

**Comment by chrisrobertsoncypress** [comment]
Clarification of above: because you are not supposed to mix blocking and unblocking code, and so I would have to propagate async all the way through the Controller layer, and I don't have the time for that right now (and anyway I believe the ASP.NET pipeline is effectively single threaded because it uses a synchronization context).

**Comment by jerriep** [comment]
@chrisrobertsoncypress Please grab the latest version from NuGet and let me know whether this resolves your issue

**Comment by chrisrobertsoncypress** [comment]
The new code (4.10.0) still blocks. I think you might have to add these lines:

StatsClient.cs : line 31
+ ConfigureAwait(false)

and

AuthenticationApiClient.cs line 231
+ ConfigureAwait(false)

Because GetImpersonationUrlAsync() is also blocking for me (I didn't mention it originally).

All the other 30 or so methods I'm using work great!

With your changes everything still works fine. I think its the things above since *everything* runs through the code you changed, and it was working fine before.

Thanks for your help!

**Comment by jerriep** [comment]
@chrisrobertsoncypress I think I have them all now 🤞

I pushed v4.3.1 and v4.10.1 to NuGet. When you get a chance you can check again.

**Comment by chrisrobertsoncypress** [comment]
Yes, that makes both methods work!

Thanks.

**Comment by jerriep** [comment]
Thanks for your feedback and your patience :)
