### ISSUE TITLE
Why do the NuGet packages depend on System.Net.Http and System.Net.Primitives

### ISSUE THREAD

**Issue by huysentruitw** [auth0/auth0.net#169]
In the nuspec files, the dependencies System.Net.Http and System.Net.Primitives are listed, but the projects itself don't need that dependency.

This gives all kind of problems in net462 / net471 scenario's see my [post on StackOverflow](https://stackoverflow.com/questions/48060230/system-reference-troubles-when-introducing-netstandard-library-dependency) which could be avoided if the Auth0 packages didn't have that dependency, or at least add an exception for `net471` that doesn't need those dependencies.

Is it possible to add support for net471, without having to add additional NETstandard packages?

**Comment by huysentruitw** [comment]
Closing this one, also see discussion at https://github.com/auth0/auth0.net/pull/170

**Comment by jerriep** [comment]
@huysentruitw Can you please give 5.0.0-beta1 a try and let me know whether it resolves this issue for you?

**Comment by huysentruitw** [comment]
@jerriep Yes, doesn't seem to add any unrelated dependency for .NET 4.7.1 now.

**Comment by jerriep** [comment]
Excellent. I'll close this one then :)
