### ISSUE TITLE
Generate token for management API?

### ISSUE THREAD

**Issue by kinetiq** [auth0/auth0.net#171]
I'm working on a basic web site, and I need to use the Management API to create some users. 

After reading about tokens, I understand that the best practice in my case is probably to generate a new token periodically.

For generating tokens, some code is provided in the docs:

```
            var client = new RestClient($"https://{Configuration["Auth0:Domain"]}/oauth/token");
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/json");
            request.AddParameter("application/json", "{\"grant_type\":\"client_credentials\",\"client_id\": \"YOURID\",\"client_secret\": \"YOURSECRET\",\"audience\": \"https://YOURINSTANCE.auth0.com/api/v2/\"}", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
```

That's fine, but isn't this included in the API somewhere? I found AuthenticationApiClient.GetTokenAsync(), but it can generate several types of token and it isn't clear which one I need, if any.

I searched the code base a little and found references to the "obsolete /oauth/token endpoint" which further compounded the feeling of being off-track.

Thanks!

**Comment by jerriep** [comment]
You should use follow this guide to understand the basics of creating a token:
https://auth0.com/docs/api/management/v2/tokens

In C# you can then use the overload of `AuthenticationApiClient.GetTokenAsync` which takes an instance of `ClientCredentialsTokenRequest`, and pass along the Client ID and Secret of the client you created (as per the guide linked to above), as well as the audience for your management API, which is something like `https://YOUR_AUTH0_DOMAIN/api/v2/`

For example

```csharp
var authenticationApiClient = new AuthenticationApiClient("mycompany.auth0.com");

// Get the access token
var token = await authenticationApiClient.GetTokenAsync(new ClientCredentialsTokenRequest
{
    ClientId = "...",
    ClientSecret = "...",
    Audience = "https://mycompany.auth0.com/api/v2/"
});
```

**Comment by kinetiq** [comment]
Thanks for the example, that worked. 

I did do a complete implementation based on that link, however as someone who is trying to make use of the C# APIs, this seems like a basic bit of guidance that would be helpful to include in the docs in the github repo. 

A small bit of feedback for on that link, which I had already been working from: the guidance feels a little vague/confusing regarding how we should handle management api tokens in production, since it seems to be more oriented on quickly getting a manual test going. I came to the conclusion that I will just generate a new token for each request and give them a very short time to live, but it doesn't actually say that's a good practice, so it leaves me feeling a bit uncertain. 

Hope that helps. Thanks!

**Comment by jerriep** [comment]
I gave your feedback to the documentation team. Thanks!

**Comment by jussimattila** [comment]
The docs I followed still point to manually creating the request using RestSharp. Please include this information in the docs, had to Google to find this simple solution.

**Comment by damieng** [comment]
@jussimattila which url still contains the RestSharp reference?  I can't seem to find it.

**Comment by jussimattila** [comment]
Sorry for the delay, missed the notification. I followed the documentation available within the portal:

![image](https://user-images.githubusercontent.com/8625258/57927802-d5091000-78b7-11e9-9b4f-2e85263560d6.png)
