### ISSUE TITLE
Set roles with namespace, in a way that is compatible with guidance

### ISSUE THREAD

**Issue by kinetiq** [auth0/auth0.net#172]
In UserCreateAsync, is there a way to configure roles that is compatible with MVC's role based auth?

I've been working off of this and some other docs:

https://auth0.com/docs/quickstart/webapp/aspnet-core/v2/04-authorization

I realize this could in theory be done using rules, but I have to create my users with Management API, and I would prefer to just set the role at that time. I've been struggling with this for a few hours - thanks!

**Comment by jerriep** [comment]
I would suggest adding the user's role to the `user_metadata` and then writing a rule which extracts it from the `user_metadata` and add it to a claim in the `id_token`.

You will then need to tell the OIDC middleware which claim contains the roles, same as we do in the code for that quickstart sample:
https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/blob/22acfe8f788e53ba7c54897881094deef45765f4/Quickstart/04-Authorization/SampleMvcApp/Startup.cs#L64

**Comment by kinetiq** [comment]
Ok great,  that was helpful. For anyone else who comes after me, here's the rule I created:

```
function (user, context, callback) {
  user.app_metadata = user.app_metadata || {};
 
  console.log('Setting roles for ' + user.email + ' (' + user.app_metadata.roles + ')');
   
  // Require a role to exist. You could definitely remove this or add a 
  // guest role; I have this here because no roles would indicate an error in
  // my user creation code.
  if (!user.app_metadata.roles) {
    console.log(user.email + ' has no role. Access denied.');
    return callback(new UnauthorizedError('No roles defined. Access denied.'));
  }

  // Set role claim, which will be picked up by .NET auth automatically.
  context.idToken['https://schemas.quickstarts.com/roles'] = user.app_metadata.roles;
    
  callback(null, user, context);   
}
```

Also, something stupid that wasted more time than necessary... Because the docs say that the namespace can be arbitrary, I set it to 'https://myinstance.auth0.com/roles' in both the script and, of course, the Auth0 config in my ASP.NET Core 2 project. That did not work and I had no idea what was wrong. I would love to know why it didn't work if you identity gurus happen to have the answer, but for anyone who reads this, just stick with 'https://schemas.quickstarts.com/roles' and save yourself some pain :)

**Comment by jerriep** [comment]
If you set the claim to `https://myinstance.auth0.com/role` in the rule and also set the `RoleClaimType` to that exact same name then it should work. If that does not work and you are 100% certain you configured everything correctly, then I suggest you open an issue with the ASP.NET team on the https://github.com/aspnet/security repo, since that is their source code

But before you do that please go over it again and ensure that everything is configured correctly, because I suspect you may have overlooked something...

**Comment by kinetiq** [comment]
You are probably correct, objectively. I am out of time on this and moving on though. :) Thanks for the help.
