### ISSUE TITLE
Missing last_password_reset from Management API User model

### ISSUE THREAD

**Issue by babelshift** [auth0/auth0.net#174]
Using the Management API to get Users such as:

`https://arxdev.auth0.com/api/v2/users/auth0|5a84916f9e044748903a7e32`

Returns a User which optionally contains a `last_password_reset` field, but the User model in this library doesn't capture that data.

`"last_password_reset": "2018-02-27T14:14:29.206Z"`

**Comment by jerriep** [comment]
@babelshift I'll look into this one for you

**Comment by jerriep** [comment]
Will be in version 5.x, due out in the next couple of weeks
