### ISSUE TITLE
Nuget package for Auth0.Core, Version=4.4.0.0 is not available

### ISSUE THREAD

**Issue by cpatterson26** [auth0/auth0.net#176]
The Auth0.AuthenticationApi, Version=4.4.0.0 [nuget package](https://www.nuget.org/packages/Auth0.AuthenticationApi/) has a reference to Auth0.Core, Version=4.4.0.0 which is not available.

The package specification lists a dependency on Auth0.Core, Version=4.0.2.0, however the Auth0.AuthenticationApi assembly throws the following exception:

> System.IO.FileNotFoundException: Could not load file or assembly 'Auth0.Core, Version=4.4.0.0,Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Image from JustDecompile:

![image](https://user-images.githubusercontent.com/37666106/37781371-f64b047c-2dc6-11e8-958e-0d3e4c84c8e3.png)

**Comment by jerriep** [comment]
@cpatterson26 Apologies for this. This is a great oversight on my side.

Please revert to version 4.3.1. I will release a new version (5.x) in the next few days which will fix the dependencies. Version 4.4 did not contain any fixes other than making 1 method as obsolete, so you can roll back safely.

**Comment by jerriep** [comment]
Version 5.0 was released which fixes this
