### ISSUE TITLE
Management API - Connection is missing metadata

### ISSUE THREAD

**Issue by yngndrw-sage** [auth0/auth0.net#178]
No connection metadata property is provided on the Connection model, making it impossible to retrieve:
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/Connection.cs
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/ConnectionBase.cs

**Comment by jerriep** [comment]
@yngndrw-sage Version 5.1 has been pushed to NuGet to resolve this. Should be available on NuGet shortly

**Comment by yngndrw-sage** [comment]
Thanks for the very quick turn-around @jerriep, the change works well.
