### ISSUE TITLE
Missing Client to Manage Email Templates

### ISSUE THREAD

**Issue by babelshift** [auth0/auth0.net#181]
The Auth0 Management API docs indicate this section of routes:
https://auth0.com/docs/api/management/v2#!/Email_Templates/get_email_templates_by_templateName

But the nuget package does not provide functionality around this.

**Comment by jerriep** [comment]
@babelshift Version 5.2.0 adds this functionality. I pushed the new release to NuGet and it should be available for you to install in about 10-20 minutes
