### ISSUE TITLE
Create strongly typed EmailProviderCredentials

### ISSUE THREAD

**Issue by jerriep** [auth0/auth0.net#183]
When sending `credentials` in the payload for configuring an email provider, the Management API checks that the correct credentials are passed, based on the provider.

The correct, long-term solution for this is to create strongly typed `EmailProviderCredentials` classes for each and every provider.

See for more discussion on this #180

**Comment by nfiles** [comment]
Is this issue still needed? I'll take a look at it if someone can point me to documentation for email providers.
