### ISSUE TITLE
Auth0.AuthenticationApi nuget package can't download.

### ISSUE THREAD

**Issue by yoichiro-manabe** [auth0/auth0.net#185]
I tryed to install `Auth0.AuthenticationApi` via nuget on mac. But can't installed with below error.

```
error: Unable to resolve 'Auth0.AuthenticationApi (>= 5.2.0)' for '.NETCoreApp,Version=v2.0'.
```

Is this package  enables on dotnet core2 ?

```
dotnet --info                                             
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

thanks.

**Comment by jerriep** [comment]
@yoichiro-manabe Yes, it works on .NET Core 2.0 applications. See below from my own computer:
<img width="1082" alt="screen shot 2018-04-29 at 12 25 17" src="https://user-images.githubusercontent.com/1006420/39403527-845d142c-4ba8-11e8-98ec-acdbf31f41b3.png">

It could be that perhaps there is an issue with your internet connection to Nuget?

**Comment by yoichiro-manabe** [comment]
@jerriep Thank you for your reply.

After I make a new project and add thhis package, it went well. So my project is any trouble.

**Comment by yoichiro-manabe** [comment]
I made a mistake in nuget config, but it workd fine fix it. Thank you.
