### ISSUE TITLE
Add GetLastApiInfo to IAuthenticationApiClient

### ISSUE THREAD

**Issue by mortenab** [auth0/auth0.net#187]
The Authentication API is subject to rate limiting (https://auth0.com/docs/policies/rate-limits) but the `IAuthenticationApiClient` does not expose the `ApiInfo` information directly.

Currently we have to do something like this:
```c#
var info = ((ApiConnection)((AuthenticationApiClient)client).Connection).ApiInfo;
```
It would be nice if it was available directly on the `IAuthenticationApiClient` interface, just like it is on the `IManagementApiClient`

**Comment by jerriep** [comment]
@mortenab Thank you for reporting this. I have pushed v5.6.0 to NuGet which adds `GetLastApiInfo()` to `IAuthenticationApiClient`. Should be available shortly.
