### ISSUE TITLE
Not able to find ttl property in PasswordChangeTicketRequest class

### ISSUE THREAD

**Issue by prabhuraaj101** [auth0/auth0.net#189]
Hi, I was trying to set expiry time for password reset ticket that is generated using PasswordChangeTicketRequest class. I was not able to assign ttl value as the class does not have that property. I upgraded to different versions of auth0 Management library, especially versions later than 4.9.0, and had no luck. Please help me fix this.

I also came across the commit https://github.com/auth0/auth0.net/pull/162/commits/3fd446d24e63b0cfcc22e05572fab8800278adbb

so I updated my nuget packege. I was not able to find it still.

**Comment by jerriep** [comment]
@prabhuraaj101 Yes, you should use the `ExpiresIn` property to set the `ttl_sec` value.

Can you please explain what is not working? Is the property sent to the API? Can you verify this with Fiddler?

**Comment by prabhuraaj101** [comment]
My intention is to set a custom expiry date for the reset password ticket.

I know for this I need to set the ttl_sec.. But I dont find the property in PasswordChangeTicketRequest.

I am attaching a screenshot.. hope it helps.

![image](https://user-images.githubusercontent.com/24266836/41517503-82939376-730f-11e8-8b57-6192f3051add.png)

**Comment by jerriep** [comment]
@prabhuraaj101 Please see the screenshot from my computer. I see the property is `Ttl`. Using v5.5.0 of the package:

![image](https://user-images.githubusercontent.com/1006420/41517672-db88af30-72e6-11e8-89da-62dfdf970ef9.png)

Are you sure you are using the latest version of the NuGet package and that it is referenced in your project correctly?

**Comment by jerriep** [comment]
No, I do not think DI has anything to do with it. That property is on the `PasswordChangeTicketRequest` class which you are instantiating directly. Please verify that you are referencing the correct version in your project.

![image](https://user-images.githubusercontent.com/1006420/41518383-5305c674-72ec-11e8-9bd9-4152a961c18b.png)

Not referencing the correct version is the only reason that I can think that this is happening. Did you check that?

**Comment by prabhuraaj101** [comment]
It looks to referenced to 5.5.0.. dont know what I am missing still

![image](https://user-images.githubusercontent.com/24266836/41518466-c4cd1d14-7316-11e8-880b-dfd37677efd6.png)

**Comment by prabhuraaj101** [comment]
Btw I am using dotnet core.

**Comment by jerriep** [comment]
My screenshots are also from .NET Core.

I honestly do not know what to tell you... Any chance you can give me access to your source code?

**Comment by prabhuraaj101** [comment]
I am afraid I can't at this moment due to company's security policies. But wondering is there any other way to set ttl on auth0(I know this may really not be the question to ask here)..

**Comment by prabhuraaj101** [comment]
You are right about dll not being referenced with proper reference.

Looks my framework version has some incompatibility with latest version of the auth0 package.

I am doing 


Update-Package -Reinstall

**Comment by jerriep** [comment]
That class has been moved to a new namespace when we migrated from v3.x to v4.x. See http://auth0.github.io/auth0.net/migrating.html

**Comment by jerriep** [comment]
I am closing this issue as it appears to be an issue on your side with the incorrect DLL versions being referenced.
