### ISSUE TITLE
LoginRequestQuery in ManagementApi is missing the Audience field

### ISSUE THREAD

**Issue by IlSocio** [auth0/auth0.net#193]
https://github.com/auth0/auth0.net/blob/v4/src/Auth0.ManagementApi/Models/Rules/LoginRequestQuery.cs

I'm using an Auth0 rule to call my own webapi endpoint in order to customize id_token and access_token. 

My webapi endpoint takes in input the RulesRequest, unfortunately, the Audience field is missing in this structure, despite Auth0 properly sends the information

Does exists an alternative way to retrieve the Audience field?

**Comment by jerriep** [comment]
Version 5.7.0 is now published with these changes
