### ISSUE TITLE
Invalid escaping of URL segments containing #

### ISSUE THREAD

**Issue by rokonec** [auth0/auth0.net#194]
**Actual behavior:**
UserClient.GetAsync("waad|id#with#hashes) throws user does not exists exception

**Expected behavior:**
UserClient.GetAsync("waad|id#with#hashes) works just fine :-)

**Possible root cause:**
Problem is in Utils.BuildUri where segments are simply escaped by Uri.EscapeUriString
which consider # as valid URI char but # is not valid in URL segments (resource id).

**Proposed solution:**
Uri.EscapeDataString shall be used instead.

**Scope & severity**
This will most probably affect every REST resource which contains # in its ID.

**Comment by jerriep** [comment]
@rokonec Version 5.8.0 has been pushed to NuGet with this fix and will be available for you to install shortly
