### ISSUE TITLE
Users.UpdateAsync ignores null fields, therefore not allowing to delete metadata properties

### ISSUE THREAD

**Issue by jaccus** [auth0/auth0.net#198]
According to [Auth0 docs](https://auth0.com/docs/metadata/apis) to delete a metadata property one should set it to null in the PATCH request:

![image](https://user-images.githubusercontent.com/1523038/42998321-15248312-8c1a-11e8-8f49-153b42021230.png)

`UsersClient.UpdateAsync` in auth0.net however, down in the `ApiConnection.cs` ignores NULL values, making deleting fields impossible:

![image](https://user-images.githubusercontent.com/1523038/42998447-6bba623c-8c1a-11e8-8fda-ce0eb43b62a7.png)

I see 2 ways to go forward with this:
1) if not necessary to ignore NULLs, remove this ignore-null behavior entirely.
2) if truly necessary to ignore NULLs in certain API calls, the ignore-null behavior should be parameterized and exposed to the user of the library.

**Comment by jerriep** [comment]
@jaccus The check to ignore nulls was added because on some API endpoints, null values were passed and Auth0 did not like that. So I will have to turn this on on specific endpoints only. Will look into this.

**Comment by jaccus** [comment]
thanks @jerriep !

Can you think of any workaround for this that does not involve manually calling the REST endpoints?

**Comment by jerriep** [comment]
I don't think so. Unless (and until) I fix it, the only "workaround" is to call those endpoints manually.

**Comment by jerriep** [comment]
@jaccus I just looked into this one in more detail, and the updating of user metadata is not affected by the null-checking you are referring to. I tested and I can indeed clear `UserMetadata` by setting the individual metadata attributes [as you can see in my unit tests](https://github.com/auth0/auth0.net/blob/bc8b036bf4be7f624c583a0fda51cae6c5b9af2a/tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs#L178-L219)

For example, lets say you have a `user_metadata` object with a property name color which is set to red:

```json
{
  "Color": "red"
}
```

If you can to clear that value, you can create the following user update request:

```cs
var updateUserRequest = new UserUpdateRequest
{
    UserMetadata = new ExpandoObject()
};
updateUserRequest.UserMetadata.Color = null;
await _apiClient.Users.UpdateAsync(newUserResponse.UserId, updateUserRequest);
```

If this is not working for you, please post me some sample code which gives you the error

**Comment by jaccus** [comment]
@jerriep I just tried your solution with an `ExpandoObject` it works despite of the null ignore setting so it's a great workaround!

If you However try using a typed object, it will not work:

```csharp
public class CustomAppMetadata
{
    [JsonProperty("color")]
    public string Color { get; set; }
}

var updateUserRequest = new UserUpdateRequest
{
    UserMetadata = new CustomAppMetadata();
};
updateUserRequest.UserMetadata.Color = null;
await _apiClient.Users.UpdateAsync(newUserResponse.UserId, updateUserRequest);
```

**Comment by jerriep** [comment]
@jaccus I think you're issue is not with the lines of code which you pointed out originally in `ApiConnection`. The problem, I believe is that the `Color` does not get serialized by JSON.NET if it is null, so the payload which gets sent to Auth0 is as follows:

```json
{
    "user_metadata": null
}
```

If you want the `color` attribute of `user_metadata` to be cleared, you need the following to be sent:

```json
{
    "user_metadata": {
        "color": null
    }
}
```

This means your need to tell the JSON.NET serializer to serialize that property, even if the value is null. Update your `CustomAppMetadata` class as follows:

```cs
public class CustomAppMetadata
{
    [JsonProperty("color", NullValueHandling = NullValueHandling.Include)]
    public string Color { get; set; }
}
```

This will hopefully resolve your issue

**Comment by jaccus** [comment]
You are very much right @jerriep - `NullValueHandling` on properties worked like charm. Thanks for helping out!

**Comment by jerriep** [comment]
No problem, glad it is sorted!
