### ISSUE TITLE
Expose server time from headers through GetLastApiInfo

### ISSUE THREAD

**Issue by Vaskinn** [auth0/auth0.net#200]
We're having a service that we want to automatically slow down its requests if we reach auth0 rate limits. Unfortunately we cannot make use of `GetLastApiInfo().RateLimit.Reset` because server time from Date header in the reponse isn't easily available to compare it to.

I suggest adding a date property to `ApiInfo` and setting its value in `ApiInfoParser.Parse()`

If you agree this is a useful idea I can create a pull request that does this.

**Comment by jerriep** [comment]
The time given back in `GetLastApiInfo().RateLimit.Reset` it the UTC time. So you can just convert your own server's time to UTC and then figure out the difference.

Will that now work for you?

**Comment by Vaskinn** [comment]
Unfortunately using the time from `Reset` alone needs the time on our server to be perfectly in sync with the time on the auth0 servers. I don't think I can trust them to be. It feels a lot safer to use the difference between two time values that are both provided by the same server.
