### ISSUE TITLE
ApiInfo not updated after error

### ISSUE THREAD

**Issue by seckford** [auth0/auth0.net#202]
I'm running into an issue in a multi-threaded app where calling GetLastApiInfo on ManagementApiClient returns null on a 429 rate limit error after the rate limit is hit on another thread.

Looking at the source for ApiConnection, in the RunAsync method, it looks like HandleErrors is throwing before ExtractApiInfo is called to populate the ApiInfo property.
```C#
            // Handle API errors
            await HandleErrors(response).ConfigureAwait(false);

            // Extract the relevate API headers
            ExtractApiInfo(response);
```
Should the call to ExtractApiInfo come before HandleErrors?

**Comment by jerriep** [comment]
@seckford I pushed v5.9.0 to NuGet to resolve this issue. Thank you for reporting 👍
