### ISSUE TITLE
AuthenticationApiClient.GetTokenAsync() is deadlocking in ASP.NET context when using Result()

### ISSUE THREAD

**Issue by chrisrobertsoncypress** [auth0/auth0.net#209]
Can you go to AuthenticationApiClient and everywhere there is an 'await' keyword can you put ConfigureAwait(false) at the end?

I usually just do a text search when writing my own code.

It looks like these were in version 4 but got taken out of version 5. Version 5 is what Nuget recommends everyone update to. When I updated it started deadlocking.

Thanks!

**Comment by damieng** [comment]
Checked in for the next release.

**Comment by robertmclaws** [comment]
Might want to add the `Microsoft.CodeQuality.Analyzers` NuGet package to the projects... catches this and other issues automatcially.
