### ISSUE TITLE
Users.CreateAsync generates exception

### ISSUE THREAD

**Issue by PlanetPayDave** [auth0/auth0.net#223]
I have the following code to create a user

```
                a0User = _managmentApiClient.Users.CreateAsync(new UserCreateRequest
                {
                    Email = user.EmailAddress,
                    Password = randomPassword,
                    Connection = "Username-Password-Authentication",
                    EmailVerified = true,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    AppMetadata = new { isActive = true }
                }).Result;
```

and the code is generating an exception with the following message 

> Insufficient scope, expected any of: create:users

The code has previously worked, however we have not created users for some time and now the code fails.  I have checked the Management API scope and create users is included, the application has the required connection included also.

I have updated to the latest NuGet packages, 5.10 and also updated to V8 Node js on the website.

What could be causing the problem?
What am I missing?

Thanks

**Comment by damieng** [comment]
Did you manage to solve this problem?  The auth0.net library does not perform this level of authorization checking itself so it must have been coming from the server.  Were you able to check the claims within the token it was using to ensure `create:users` was there?

**Comment by PlanetPayDave** [comment]
I had forgotten I had raised this issue, it was so long ago.  It is probably fixed now
