### ISSUE TITLE
"token_lifetime_for_web" property missing from ResourceServer and ResourceServerBase class

### ISSUE THREAD

**Issue by dmarjoram** [auth0/auth0.net#224]
It's currently not possible to use set or update the token expiry for browsers via the SDK due to the token_lifetime_for_web JSON property not having an associated property in the ResourceServer and ResourceServerBase classes.

Can these please be added.

I see someone has already created a pull request for this here:
https://github.com/auth0/auth0.net/pull/208

**Comment by jmn8718** [comment]
the PR has been merged

**Comment by damieng** [comment]
Shipped in 5.11.0 (out now)
