### ISSUE TITLE
No passwordlessLogin / verification

### ISSUE THREAD

**Issue by dapug** [auth0/auth0.net#227]
StartPasswordlessSmsFlowAsync exists and works.  But then there is no PasswordlessLogin to complete the process.   Is this by design? And if so, why even have the Start method?

https://auth0.com/docs/libraries/auth0js/v9#verify-passwordless

**Comment by damieng** [comment]
[The `password/verify` feature has not been available for new tenants since June 2017](https://auth0.com/docs/api/authentication#authenticate-user) so we have no plans to further expose it in SDK APIs.

**Comment by celluj34** [comment]
So then how do I programmatically verify a user's one time password?

**Comment by damieng** [comment]
I believe the recommended course of action is to use the universal login page.  Auth0 support should be able to supply more guidance if you reach out to them.
