### ISSUE TITLE
Use of BuildAuthorizationUrl

### ISSUE THREAD

**Issue by PlanetPayDave** [auth0/auth0.net#228]
Hello

I am currently using the `BuildAuthorizationUrl ` in my C# MVC account controller login function to build the URL for login, the domain name I pass to the function is _ourdomain_.eu.auth0.com.

I am trying to change the colour of the login button, is this possible using the `WithValue` function of `BuildAuthorizationUrl ` in the same way it is possible to select a new logo or do I have to do something with a style sheet?

When I inspect the login page, I see the following HTML

`<button class="auth0-lock-submit" type="submit" style="background-color: rgb(234, 83, 35);"><div class="auth0-loading-container"><div class="auth0-loading"></div></div><span class="auth0-label-submit"><!-- react-text: 69 -->Log In<!-- /react-text --><span><svg focusable="false" class="icon-text" width="8px" height="12px" viewBox="0 0 8 12" version="1.1" xmlns="http://www.w3.org/2000/svg"><g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="Web/Submit/Active" transform="translate(-148.000000, -32.000000)" fill="#FFFFFF"><polygon id="Shape" points="148 33.4 149.4 32 155.4 38 149.4 44 148 42.6 152.6 38"></polygon></g></g></svg></span></span></button>`

I assume that this is the default HTML coming from the Auth0 script

`<script src="https://cdn.auth0.com/js/lock/11.3/lock.min.js"></script>`

I have tried adding a "auth0-lock-submit" class to my site.less but this has no affect on the login page.  I assume that is because at the time the login page is showing it is not on my site.

How do I simply change the colour of the button?

I would also like to know if it is possible to change the icons on the username and password edit controls.

If this is not the correct area for this question then please let me know where to ask.

Thanks

**Comment by damieng** [comment]
Hi there.  

The login itself as you noticed is actually performed by auth0.com using our lock.js solution.  Full details about customizing that can be found here https://auth0.com/docs/libraries/lock/v11/configuration
