### ISSUE TITLE
Permissions endpoints

### ISSUE THREAD

**Issue by christophano** [auth0/auth0.net#246]
I see that role endpoints were recently included (#241), but this change didn't include the permissions endpoints that exist on roles and users. Are there any plans to include them?

**Comment by damieng** [comment]
Merged in for 6.0 - thanks for spotting this.

**Comment by christophano** [comment]
Fantastic stuff! I've been working off a fork where I implemented this (on roles, at least) to get me going, but I'm pleased that official support is on its way!
