### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by Rixi2203** [auth0/auth0.net#249]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

[ ] I have checked the [documentation for this library](https://auth0.github.io/auth0.net/).

[ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[ ] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.net/issues) and [PRs](https://github.com/auth0/auth0.net/pulls).

[ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.NET used: 
- Version of .NET used:
- Any other relevant environmental versions:
- Additional libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Log files (redact/remove sensitive information)
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by damieng** [comment]
This is our default template with no details filled in.  If you re-edit this issue with actual details I will reopen.
