### ISSUE TITLE
Google Login - How to set access_type=offline

### ISSUE THREAD

**Issue by facu-larocca-zenfolio** [auth0/auth0.net#262]
### Description

I need to interact with Google Calendar API, in order to do so, I need my users to login with Google so that I can get google `access_token`. I can achieve that and it is actually working. Once I've got the user logged in with Google, I can query the user's profile and get `google-oauth2` identity as stated [here](https://auth0.com/docs/connections/calling-an-external-idp-api).

The problem is that I am not getting back the `refresh_token` required for when the google `access_token` expires.
According to [Google's Documentation](https://developers.google.com/identity/protocols/OAuth2WebServer#offline), it is required to send a query parameter `access_type=offline`.

Using the SDK, I could not find a way to solve this issue. I am not sure then whether it is an issue at all or it is just me not realizing how to do it. I apologize in case I am in the second case, while at the same time I ask for help.

### Prerequisites

- [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.net/).

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.net/issues) and [PRs](https://github.com/auth0/auth0.net/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.NET used: Auth0.AuthenticationApi 6.1.0
- Version of .NET used: Asp.Net Core 2.2

### Reproduction

1. Build a Google Login Uri using `AuthorizationUrlBuilder.BuildAuthorizationUrl()`

```c#
public string GetGoogleLoginUrl(string redirectUri, string antiForgery)
{
    Auth0AuthorizationUrlBuilder urlBuilder =
        _auth0Context.CreateAuthenticationApiClient().BuildAuthorizationUrl();
    urlBuilder.WithResponseType(AuthorizationResponseType.Code);
    urlBuilder.WithClient(_settings.BackendClientId);
    urlBuilder.WithAudience(_settings.FrontendAudience);
    urlBuilder.WithConnection(Constants.ConnectionTypeGoogle);
    urlBuilder.WithState(antiForgery);
    urlBuilder.WithRedirectUrl(redirectUri);
    urlBuilder.WithScope(AuthorizationUtils.AllScopeNames + " access_offline");
    Uri url = urlBuilder.Build();
    return url.AbsoluteUri;
}
```

2. Exchange the authorization code using `AuthenticationApiClient.GetTokenAsync()`
3. Verify the user has logged in successfully 
4. Get an `access_token` to call the Management API `https://{MY_DOMAIN}/oauth/token`
5. Get user profile
```
curl --request GET \
  --url 'https://{MY_DOMAIN}/api/v2/users/{USER_ID}' \
  --header 'authorization: Bearer {ACCESS_TOKEN_FROM_STEP_4}'
```
6. Verify that `refresh_token` is not included within google identity
```
{
  // More info
  "user_id": "{USER_ID}", //looks like google-oauth2|000000000000000000000
  "identities": [
    {
      "provider": "google-oauth2",
      "access_token": "valid access token",
      "expires_in": 3599,
      "user_id": "000000000000000000000",
      "connection": "google-oauth2",
      "isSocial": true
    }
  ],
  // More info
}
```

**Comment by dlemstra** [comment]
I don't have any experience with this library so I could be wrong but it looks like you are setting the scope instead of a query parameter. I think you should do this instead:

```C#
urlBuilder.WithScope(AuthorizationUtils.AllScopeNames);
urlBuilder.WithValue("access_type", "offline")
```
