### ISSUE TITLE
Unable to update given_name, family_name or name of user

### ISSUE THREAD

**Issue by robert-mccausland** [auth0/auth0.net#263]
### Description

I am trying to update the `family_name`, `given_name` and `name` of users though the management API, these are listed as available in the [api documentation](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id), but I cant find the option in the `UpdateUserRequest` model. I think this is a similar issue to #77 but with the update API instead.

Would it be possible to include these extra fields in the `UpdateUserRequest`?

**Comment by robert-mccausland** [comment]
Thanks for the quick response to this guys 👍

**Comment by damieng** [comment]
Shipped now in 6.2.0
