### ISSUE TITLE
Get Guardian Enrollments

### ISSUE THREAD

**Issue by AndrewStratigos** [auth0/auth0.net#270]
Hi Auth0,
   I noticed that the "GetEnrollments" method is missing on this .Net client.
   There was a an [issue ](https://github.com/auth0/auth0.net/issues/163)raised about this, and was closed March 2019. I think its still outstanding.

   I believe this method might have been overlooked (because its a guardian method on the user)
       [/api/v2/users/{id}/enrollments](https://auth0.com/docs/api/management/v2#!/Users/get_enrollments)

### Description

Looking to pull a list of guardian enrollments for a user (this has been done but we are porting from the javascript librrary to .net

- List guardian enrollments for a user (particularly enrollmentId so they can unenroll themselves.)

### Prerequisites

[yes] I have checked the [documentation for this library](https://auth0.github.io/auth0.net/).

[yes] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts. [This was the nearest.](https://community.auth0.com/t/multiple-guardian-enrollments/11808)

[yes] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.net/issues) and [PRs](https://github.com/auth0/auth0.net/pulls).

[yes] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md). 

[yes] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.NET used: 6.3.0
- Version of .NET used: .Net Core 2.2
- Any other relevant environmental versions:
- Additional libraries that might be affecting your instance:

**Comment by damieng** [comment]
Looks like InvalidateRememberBrowserAsync and GenerateRecoveryCode were also missing.  I have a PR up for it now.
