### ISSUE TITLE
Add search across all connections

### ISSUE THREAD

**Issue by eugeniop** [auth0/auth0.net#29]
https://auth0.com/docs/api#!#get--api-users-search--criteria-

**Comment by jerriep** [comment]
@eugeniop @dschenkelman  Gentleman, I am doing some housekeeping of old issues. Since V2 of the SDK we support new endpoint at https://auth0.com/docs/api/v2#!/Users/get_users

Is assume this issue is not relevant anymore?

**Comment by jerriep** [comment]
Please reopen if this is still an issue
