### ISSUE TITLE
Setting the client id for the verification email

### ISSUE THREAD

**Issue by jamesgoldswain** [auth0/auth0.net#292]
According to the documentation the verification email request should be able to handle a "client_id" in a request: 
https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

However in 
https://github.com/auth0/auth0.net/blob/f676441b5915923221e963b08715eae207cc3beb/src/Auth0.ManagementApi/Models/VerifyEmailJobRequest.cs#L17

There is no property available for setting this in the request from the .NET client, should this be available?

Something along the lines of 

```
        /// <summary>
        /// The id of the client, if not provided the global one will be used
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }
```

**Comment by jamesgoldswain** [comment]
Sounds good, I'll get onto that thanks!

**Comment by damieng** [comment]
Looking at getting a release out very soon - do you still want to do this or should I go ahead?
