### ISSUE TITLE
Add support for the verification_ticket endpoint

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0.net#30]
When sending out custom verification emails (eg: I generate my own mail and send it out with SendGrid) we need a way to have the email address verified in Auth0. The API exposes the verification_ticket endpoint which generates an url that can confirm the email address. This endpoint is not available in the .NET SDK.

Docs: https://auth0.com/docs/api#!#post--api-users--user_id--verification_ticket

**Comment by jerriep** [comment]
Supporting new endpoint (https://auth0.com/docs/api/v2#!/Jobs/post_verification_email) since V2 of SDK.
