### ISSUE TITLE
Testable - Concrete type ManagementApiClient

### ISSUE THREAD

**Issue by stephenstroud** [auth0/auth0.net#316]
I want to unit test method scopes using ManagementApiClient, however, this isn't possible. Please introduce virtual so I can fake the class?

**Comment by damieng** [comment]
We have a PR open to help testing at #314 that will let you wire up an alternative connection for simple mocking/stubbing.

**Comment by jtbruch-fixdrepair** [comment]
@damieng looks like that PR was closed, is there a different PR that is going to make it in instead?  I am running into the same issue.

**Comment by damieng** [comment]
The first one for the testability of auth is at #321 - there will be an almost identical one for management later today!

Basically you will be able to mock out the whole of the management API by just implementing an interface that has two methods - one for handling get request and another for other http requests.

**Comment by jtbruch-fixdrepair** [comment]
Beautiful! Thank you so much for the quick response :) @damieng

**Comment by jtbruch-fixdrepair** [comment]
@damieng thank you so much for your work on getting this testable for the group! Quick question, I saw you tagged this 7.0.0, what is your plan for releasing all this great work? :)

**Comment by damieng** [comment]
We don't give firm timelines out for SDK release dates as they tend to happen when they're ready.  That said this is my top priority right now and the only remaining work is this + a tying in the symmetric id token validation.

**Comment by jtbruch-fixdrepair** [comment]
Sounds good.

**Comment by damieng** [comment]
Merged in, will ship in 7.0.0 - docs on how to use it will be in the migration guide.

**Comment by stephenstroud** [comment]
Great!
