### ISSUE TITLE
EnrollmentAuthMethod enum contains invalid option "authnetication" instead of "authenticator"

### ISSUE THREAD

**Issue by filiptesar** [auth0/auth0.net#322]
### Description

Management API EnrollmentsResponse  cannot be parsed because of invalid value in enum EnrollmentAuthMethod. It contains "authentication" instead of "authenticator". 

See https://auth0.com/docs/api/management/v2/#!/Users/get_enrollments:
auth_method string (optional) Enrollment type
["authenticator" or "guardian" or "sms"]

### Reproduction

1. Enable MFA with OTP option and let user to activate MFA using Google Authenticator.
2. Ty to get user's MFA enrollments using Users.GetEnrollmentsAsync method
3. Exception is thrown because the actual value in EnrollmentsResponse.AuthMethod is "authenticator" and not "authentication"

### Environment

- Version of this library used: 6.5.4

**Comment by filiptesar** [comment]
Hi, when can I expect the fix to be released?

**Comment by damieng** [comment]
Given that the upcoming 7.0.0 release has breaking changes and will be in beta for a week we've gone ahead and published 6.5.5 that includes this fix.  It should be available no NuGet now.
