### ISSUE TITLE
Migration guide for 7.0.0

### ISSUE THREAD

**Issue by damieng** [auth0/auth0.net#344]
Many breaking changes have happened in 7.0.0 - we need a migration guide to help developers migrate to the new version detailing any necessary tweaks they will need to make to adopt it and how to take advantage of the new features.

**Comment by jtbruch-fixdrepair** [comment]
@damieng thank you so much for all the great work you have done on this.  Our team has *just* started integrating Auth0 into our platform, and I was wondering if this would be an opportunity for us to help each other out in terms of documentation.  Feel free to completely shoot down, and I am not entirely sure of Auth0's policy on this.  

I was wondering if it would be possible to do an `7.0.0-earlyversion` so I/my team can be your guinea pig and help document as an additional set of eyes.  We are early on in the development so we don't have any dependencies on breaking changes.  

Anyways - like I said, not sure if this is possible, but if so let me know and I'll be more than happy to help out where I can!

Thanks,
JT

**Comment by damieng** [comment]
I did consider putting out a 7.0.0-beta1 given the number of changes in this release but wasn't sure if enough people would try it or even see it exists given the nuget defaults of hiding pre-release versions.

If you're willing to give it a try I'm willing to publish it ahead of the migration guide.  I'd also love any feedback or confusion on adopting it.

There's one more piece of work to go in which is for caching the JWKS documents but then it should be ready for a beta.

**Comment by jtbruch-fixdrepair** [comment]
That would be great if you wanted to do that.  I would absolutely give any feedback/confusion about it.

**Comment by dandenton** [comment]
I'll try the beta once you have it the nuget up.  We're mostly doing user/role management through the API and it'd be good to see the interface changes for our unit tests too.

**Comment by damieng** [comment]
Fixed in #362
