### ISSUE TITLE
Ability to SetUri after client has been initialised 

### ISSUE THREAD

**Issue by robdavey555** [auth0/auth0.net#370]
I would like the ability to switch baseUri once AuthenticationApiClient has been instantiated. We have a service that deals with multiple auth0 tennents and need the service to be able to switch between these tenants.

**Proposed solution**

Remove readonly from `Uri tokenUri;` variable

Add method to update baseUri
```
public void SetUrl(Uri baseUri)
{
   BaseUri = baseUri;

   tokenUri = BuildUri("oauth/token");
}
```

**Comment by damieng** [comment]
ASP.NET is highly multi-threaded and we have designed these classes so instances can be shared between threads.

Adding a settable Uri would break `AuthenticationApiClient`'s thread-safety. Consider the scenario:

a. Thread A sets baseUri to https://sitea.com
b. Thread B sets baseUri to https://siteb.com
c. Thread A performs it's operations and inadvertently uses siteb.com

`AuthenticationApiClient` itself is very light-weight if you share `HttpClientAuthenticationConnection` between them. So you could instead create an `AuthenticationApiClient` on-demand passing in a shared instance of `HttpClientAuthenticationConnection` or alternatively store the `AuthenticationApiClient` instances in a dictionary perhaps keyed by Uri.

**Comment by robdavey555** [comment]
@damieng That all makes sense. Thanks for the quick reply,
