### ISSUE TITLE
Id token is validated even if it's not requested

### ISSUE THREAD

**Issue by asoltys1** [auth0/auth0.net#372]
Hi,
I faced an issue with the following steps to reproduce
1) Requesting a token via resource owner password flow ( _AuthenticationApiClient.GetTokenAsync( ResourceOwnerTokenRequest request)_ )
2) scope param doesn't contain 'openid' 

It causes the IdTokenValidationException("ID token is required but missing.") to be thrown because  id token is checked for presence.But I think you shouldn't do this if the openid token is not specified

Auth0 .NET version 7.0.1
.NET Core 3.1

**Comment by damieng** [comment]
Hi.

Version 7 of this library now requires ID tokens to always be present and so `openid` scope should always be requested. This is part of our on-going OpenID Compliant efforts.

It would seem that the release notes did not call this out - my apologies for that.

**Comment by ghills** [comment]
I also ran into this same issue when trying to migrate to v7 of the SDK as we use a couple of silent auth steps after the initial login to grab API tokens and one of them didn't include `openid` on the scopes. It would be helpful if a note about this were added to https://auth0.github.io/auth0.net/migrating-to-v7.html as that is what I referenced when doing the upgrade.
