### ISSUE TITLE
ConfigureAwait(false) needed in Auth0.ManagementApi.HttpClientManagementConnection

### ISSUE THREAD

**Issue by cecilyth** [auth0/auth0.net#373]
### Description

Calling methods on the ManagementApiClient resulted in deadlock because of missing .ConfigureAwait(false).

I was able to fix the issue by adding the ConfigureAwait(false), I'm happy to open a pull request if desired.

### Environment

Latest nuget version, WPF service stack application.

**Comment by damieng** [comment]
You're right! I see two missing ones - GetAsync and SendAsync.  I can either add them or accept a PR - also would be needed on HttpClientAuthenticationConnection.

**Comment by cecilyth** [comment]
> You're right! I see two missing ones - GetAsync and SendAsync. I can either add them or accept a PR - also would be needed on HttpClientAuthenticationConnection.

Great! If it's easy for you to add them quickly then that works for me! Thanks so much!

**Comment by damieng** [comment]
Fixed in 7.0.2
