### ISSUE TITLE
Handling mfa_required for oauth/token endpoint

### ISSUE THREAD

**Issue by drjaydenm** [auth0/auth0.net#376]
Hi there, when fetching an access token via the `oauth/token` endpoint, if you get an `mfa_required` error, there is no way to retrieve the `mfa_token` field from the `ApiException` that is thrown.

I can see this issue was solved with the Java SDK, https://github.com/auth0/auth0-java/issues/119
Would it be possible to pass back the `mfa_token` either as a property on this exception, or perhaps as part of the exception data?

Without this, we will have to hand craft our authentication requests to `oauth/token`

Thanks

**Comment by drjaydenm** [comment]
Hi @damieng, we are looking at building out our solution for MFA in the next couple of days, do you think this functionality would be ready in this SDK by then? If not, we will look at rolling our own solution using `HttpClient` directly. Thanks

**Comment by damieng** [comment]
This should be doable as a short-term fix by adding a Dictionary to the ApiError to obtain the extra parameters. I'll look into what's involved in changing the deserializer.

**Comment by drjaydenm** [comment]
I was thinking along those lines as well, perhaps a `Dictionary<string, string>` with the `[JsonExtensionData]` attribute applied which should pickup any un-mapped values automatically

**Comment by damieng** [comment]
Shipped in 7.0.3. You can now use `apiData.ExtraData["mfa_required"]`

**Comment by drjaydenm** [comment]
Thanks @damieng, it's working great
