### ISSUE TITLE
Update documentation how to run tests

### ISSUE THREAD

**Issue by SychevIgor** [auth0/auth0.net#387]
### Description
There are multiple configuration settings missed from readme.md file. Screenshot of start page
![image](https://user-images.githubusercontent.com/578954/78540306-a3b16f80-77fc-11ea-9697-885dada37eab.png)
In tests for example - missed following configs:
![image](https://user-images.githubusercontent.com/578954/78540325-aca24100-77fc-11ea-9700-2adf5edc98fb.png)
![image](https://user-images.githubusercontent.com/578954/78540620-19b5d680-77fd-11ea-92b2-b86a52c826b4.png)

Please, update readme.md file to simplify contribution process.

**Comment by damieng** [comment]
The snippet defines the *format* not the explicit full list. 

Really even having a full list would not help as to run the full integration tests you'd need 5 tenants with very specific configurations and some paid plans.

We run the integration tests locally before merging in PRs. It's not ideally but it's where we're at. What specifically are you looking to work on?

**Comment by SychevIgor** [comment]
Maybe in this case- section about a way to run tests- could be removed? It's not answering on "how to contribute" and only confusing. 

I've try to better understand the source code of an sdk to debug my own application and compare side by side- what my application send/receive and what samples send/receive.
