### ISSUE TITLE
Support System.Text.Json

### ISSUE THREAD

**Issue by mattbarry** [auth0/auth0.net#389]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The System.Text.Json namespace provides functionality for serializing to and deserializing from JavaScript Object Notation (JSON). The library design emphasizes high performance and low memory allocation over an extensive feature set.

### Describe the ideal solution

Remove Newtonsoft.Json from Auth0.Core.csproj and use System.Text.Json instead.

### Additional context

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to

**Comment by damieng** [comment]
This is unfortunately not possible at this time as System.Text.Json is not supported on .NET Framework 4.5.2 that we currently support.

We would need to drop support for everything prior to .NET Framework 4.7.2 for that migration to happen so we'd need to consider that for the next major based on current usage statistics for this library.

**Comment by damieng** [comment]
I'm going to tag it to the next major so we can consider it then.

**Comment by sandromastronardi** [comment]
How about Utf8Json which is one of the fastest JSON parsers? (or allow developers to select their own?)

**Comment by kyrylo-prescryptive** [comment]
I still forced to use _Newtonsoft.Json_ to work if _Auth0.ManagementApi_. Hope devs will support _System.Text.Json_

**Comment by davidruhmann** [comment]
@frederikprijck Could this issue be reopened and possibly added to a milestone now that [4.5.2 is EOL](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework) and removed from this library as of https://github.com/auth0/auth0.net/pull/687?

This project supports back to `4.6.2` and the latest [`System.Test.Json`](https://www.nuget.org/packages/System.Text.Json/8.0.0) also supports back to `4.6.2`.
