### ISSUE TITLE
Support Bulk User Exports Job via Auth0 Management API

### ISSUE THREAD

**Issue by talouv** [auth0/auth0.net#395]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> As described https://auth0.com/docs/users/search/v3/get-users-endpoint#limitations we want to use the management api to performt user exports.
> As it stands right now, the Auth0.ManagementApi nuget package does not support the User Export jobs.
> In short, we want the Auth0.ManagementApi to support bulk user exports (including some way to retrieve the export result), i.e. https://auth0.com/docs/users/guides/bulk-user-exports
>
> We want to use the Auth0.ManagementApi to leverate its functionality on rate limits, etc.

### Describe the ideal solution

> We would like the Auth0 Management api to support the user export job such that we can start an export job in a way similar to this:

```
using (var client = await GetManagementApiClientAsync(domain, clientId, clientSecret))
{
	var jobId = await client.Jobs.ExportUsersAsync(new ExportUsersRequest
	{
		Format = "json",
		Fields = new object[]
		{
			new
			{
				name = "user_id",
				export_as = "userId"
			},
			new
			{
				name = "email"
			},
			new
			{
				name = "name"
			},
			new
			{
				name = "user_metadata.name",
				export_as = "metadataName"
			},
			new
			{
				name = "blocked"
			}
		}
	});
}
```

> We want to be able to retrieve the (finished) task status in a way similar to this:

```
using (var client = await GetManagementApiClientAsync(domain, clientId, clientSecret))
{
	var exportJob = await client.Jobs.GetAsync(taskId);

	var stream = await client.Jobs.GetTaskResultStreamAsync(exportJob.Location);
	using (var gZipStream = new GZipStream(stream, CompressionMode.Decompress))
	using (var streamReader = new StreamReader(gZipStream))
	using (var jsonTextReader = new JsonTextReader(streamReader))
	{
		// Handle...
	}
}
```

> or maybe just something similar to

```
using (var client = await GetManagementApiClientAsync(domain, clientId, clientSecret))
{
	var exportJob = await client.Jobs.GetAsync(taskId);

	using (var httpClient = /* Get an authenticated http client somehow */)
	{
		var stream = await httpClient.GetStreamAsync(exportJob.Location);
		using (var gZipStream = new GZipStream(stream, CompressionMode.Decompress))
		using (var streamReader = new StreamReader(gZipStream))
		using (var jsonTextReader = new JsonTextReader(streamReader))
		{
			// Handle...
		}
	}
}
```

> The point is just that we will need the location property, and maybe a way to download the result file.

## Alternatives and current work-arounds

> Request the api directly, not using the Auth0 Management API.

### Additional context

>

**Comment by frederikprijck** [comment]
Hi @talouv ,

Sorry for the delayed response. I opened a PR to address this, please feel free to have a look: https://github.com/auth0/auth0.net/pull/436

Note we only added a way to start the export. Retrieving the job to check if it is complete can be done using the existing API. Downloading the CSV/JSON file can be achieved outside of our SDK.
