### ISSUE TITLE
Case of email addresses should be normalized

### ISSUE THREAD

**Issue by mattgrande** [auth0/auth0.net#396]
### Description

(Please note: I'm not sure if this is an issue with the Auth0.Net library, or with Auth0's infrastructure as a whole)

Due to legacy concerns in our codebase, it made more sense for us to "roll our own" Auth0 import. When the application goes online, it checks to see if each user is already within our Auth0 system and, if not, imports them. It worked great for almost every user.

However, we discovered one user with an uppercase character in their email address (eg, `Abc@example.com`). The user was saved in Auth0 with `abc@example.com`.

This means that when we check if the user exists 

    ManagementApi.Users.GetUsersByEmailAsync(email);

it returns no records. So we try to create the user:

    ManagementApi.Users.CreateAsync(ucr);

Which fails with an exception:

    Auth0.Core.Exceptions.ErrorApiException: The user already exists.

### Reproduction

    var email = "Abc@example.com";
    var ucr = new UserCreateRequest
    {
        // Set the connection, name, password, etc...
        Email = email
    };
    await ManagementApi.Users.CreateAsync(ucr);
    // Should succeed!
    
    // Now verify the user exists
    IList<User> users = await ManagementApi.Users.GetUsersByEmailAsync(email);
    Console.WriteLine(users.Count);  // Is 0; should be 1

### Environment

> Please provide the following:

- **Version of this library used:** Auth0 Management API 7.0.1
- **Version of the platform or framework used, if applicable:** .Net 4.7.2
- **Other relevant versions (language, server software, OS, browser):** Same issue across all tested
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by damieng** [comment]
Hi.

As an SDK-wide rule we do not modify the values passed to us before sending to the server or modify the data coming back. Instead the Management SDK acts merely as a strongly-typed conduit between the C# and the underlying REST endpoint.
