### ISSUE TITLE
Missing call to fire change password email

### ISSUE THREAD

**Issue by oliverjanik** [auth0/auth0.net#398]
Using version 7.0.5

Hello, this page here describes a call that triggers Change password email: https://auth0.com/docs/connections/database/password-change#use-the-authentication-api

```
curl --request POST \
  --url 'https://YOUR_DOMAIN/dbconnections/change_password' \
  --header 'content-type: application/json' \
  --data '{"client_id": "YOUR_CLIENT_ID","email": "","connection": "Username-Password-Authentication"}'
```

This endpoint does not seem to be covered by this library?

I found `Auth0.ManagementApi.Clients.TicketsClient.CreatePasswordChangeTicketAsync`, that however just generates a link, does not send an email.

**Comment by damieng** [comment]
https://github.com/auth0/auth0.net/blob/b7d2d8e0b6034aed46f07f83b06adc62553fd4a7/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs#L72 should be what you are looking for.
