### ISSUE TITLE
Remove Users From Role

### ISSUE THREAD

**Issue by Rocinante89** [auth0/auth0.net#404]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> It is simple to add users to a role using the AssignUsersAsync call, however no such RemoveUsersAsync call exists, making it unclear how to remove users.

### Describe the ideal solution

> Ideally, there should be a public Task RemoveUsersAsync(string id, AssignUsersRequest request) available so that we can easily remove users in roughly the same way as we add them.

**Comment by damieng** [comment]
Unfortunately there is no server-side API available to perform this operation that the client can take advantage of.

As a workaround you can use `Users.RemoveRolesAsync` to remove one user from a role at a time.

**Comment by Rocinante89** [comment]
@damieng cheers, that should work nicely actually!

**Comment by damieng** [comment]
Great, thanks for letting me know!
