### ISSUE TITLE
Add 'connection' property to the UserBlock class

### ISSUE THREAD

**Issue by scottyb86** [auth0/auth0.net#405]
Hello,

Earlier I created the following issue: https://github.com/auth0/auth0.net/issues/386

I was then referred to the Auth0 support center, and created the following ticket there: https://support.auth0.com/tickets/00454344

After a little bit of back and forth and some testing the endpoints directly using postman, it was recommended that in order to further filter out these user blocks I should use the connection field. I am currently able to see that 'connection' returned in the data when using postman.

![image](https://user-images.githubusercontent.com/1817622/81008475-ff354400-8e20-11ea-8c31-92006c88cde3.png)

Is it possible to include the 'connection' property in the UserBlock class in the SDK? This would allow me to filter out any userblocks with duplicate identifiers in separate connections.

Thanks,
Scott

**Comment by stevehobbsdev** [comment]
Thanks for raising @scottyb86 - #406 has been raised and is going through our PR process now.
