### ISSUE TITLE
Removing individual metadata properties doesn't work

### ISSUE THREAD

**Issue by gregsdennis** [auth0/auth0.net#408]
### Description

The management API client doesn't allow removal of specific properties from metadata.

### Reproduction

```c#
var updateRequest = new UserUpdateRequest
	{
		AppMetadata = new
			{
				propertyToRemove = (string) null,
				prepertyToKeep = "don't delete me, bro"
			}
	};

await _managementClient.Users.UpdateAsync(userId, updateRequest);
```

### Environment

- **Version of this library used:** 7.0.4
- **Version of the platform or framework used, if applicable:** .Net Core 3.1

### Notes

Using Fiddler, I discovered that null properties aren't included during serialization.  So while I would expect the request to be serialized as

```json
{
  "propertyToRemove": null,
  "propertyToKeep": "don't delete me, bro"
}
```

the data actually sent to the API is

```json
{
  "propertyToKeep": "don't delete me, bro"
}
```

The API then merges this data with what's already on the user.

**Comment by stevehobbsdev** [comment]
Hey @gregsdennis, apologies for the delay here. Just interested in the use case for sending `null` here for something like `propertyToRemove` - couldn't you consider the lack of existence of the property on the serialized object and `null` to be equivalent?

I'll look deeper into why that's occurring, just wondering if there's another way to unblock you in the meantime.

**Comment by gregsdennis** [comment]
That would be fine, except that the API documents that for metadata is a PATCH operation, except that it doesn't actually use JSON Patch syntax.  It says that it works by merely merges results.  In such an operation, the absence of a property is ignored, whereas sending a `null` would be explicitly removing a property.

Ref: https://auth0.com/docs/users/guides/update-metadata-properties-with-management-api

**Comment by nickwilliams-codynamic** [comment]
Hit this myself recently. It would be really good if this could be 'fixed' as it is counter intuitive to the expected behaviour of auth0s PATCH. In the meantime, we did find a workaround. Haven't looked into why this works.

If `AppMetadata` is assigned to an `Expando` object rather than an annoymous object the null properties are sent in the HTTP request.

``` c#
dynamic expando = new ExpandoObject();
expando.propertyToRemove = null;
expando.prepertyToKeep = "don't delete me, bro";

var request = new UserUpdateRequest()
{
  AppMetadata = expando
};
```

Body of request is then:

```json
{
   "app_metadata":{
      "propertyToRemove":null,
      "prepertyToKeep":"don't delete me, bro"
   }
}
```

**Comment by stevehobbsdev** [comment]
Thanks @nickwilliams-codynamic  - @gregsdennis would this workaround be acceptable in the meantime?

**Comment by damieng** [comment]
I think that's basically a side-effect of how the JSON.NET serializer is working/configured.

In JS there's the option of undefined vs null to allow whether you're not setting data or you are specifically removing the value. In .NET we only have null so all the patch operations become somewhat more difficult.

One option would be to add property change tracking to the PATCH models and have that honored by the serialiation paths. If a property was changed it gets serialized even if the new value is null - if it is not changed then it is not sent.

**Comment by gregsdennis** [comment]
I'll try the `ExpandoObject`, but having to explicitly specify that type is strange since it's a "behind the scenes" type that's used to make `dynamic` work.

@damieng I think you're right about the JSON.Net serializer.  It can be configured to include null/default values.  This is the change that should take place.

**Comment by gregsdennis** [comment]
> One option would be to add property change tracking to the PATCH models and have that honored by the serialiation paths. 

Another option is to actually support [JSON Patch](http://jsonpatch.com/).

**Comment by Rudde** [comment]
Well, it's still a problem 2 years later

**Comment by mlpl92** [comment]
Try to use in AppMetadata model [JsonProperty( NullValueHandling = NullValueHandling.Include)]. It works in my case.
