### ISSUE TITLE
Device authentication flow in the AuthenticationApi

### ISSUE THREAD

**Issue by sandromastronardi** [auth0/auth0.net#409]
### Describe the problem you'd like to have solved

The Device authentication flow is now not implemented in the Authentication API

### Describe the ideal solution

It would be nice if I didn't have to develop a custom implementation for that

## Alternatives and current work-arounds

I'm building my own but it would be nice to have it here...

**Comment by sandromastronardi** [comment]
I guess this is still relevant if it isn't solved...

**Comment by frederikprijck** [comment]
Thanks for reporting this @sandromastronardi and sorry for the delayed response! 
I will have a discussion with the team on supporting the Device Authorization Grant.

**Comment by sandromastronardi** [comment]
Thanks

**Comment by acraven** [comment]
@frederikprijck I have some code for calling the two endpoints as described in https://auth0.com/docs/flows/call-your-api-using-the-device-authorization-flow. It will no doubt be similar to that of @sandromastronardi 

Both methods would fit nicely in https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs; I have a new `StartDeviceFlowAsync` method and another overload of `GetTokenAsync`

My implementation of `GetTokenAsync` currently polls as per the interval, but it might be more appropriate to move that up the stack.

Only a spike, so no tests, but happy to discuss.

**Comment by frederikprijck** [comment]
Hi @acraven,

That sounds very interesting. If it doesn't take too much effort, would u be willing to open a PR so we can discuss?

As you mentioned, I would remove the polling from our SDK and leave that to the caller.
No need to worry about tests just yet, let us have a look and discuss first, then you can finalize things.

**Comment by acraven** [comment]
Will do @frederikprijck.

**Comment by acraven** [comment]
Let me know your thoughts @frederikprijck
