### ISSUE TITLE
GetTokenAsync fails when using HS256 with a client secret containing an underscore

### ISSUE THREAD

**Issue by shri-aithal** [auth0/auth0.net#410]
### Description
I maintain a legacy ASP.NET WebForms application which uses Auth0. It has been using an old Auth0 .NET SDK library, which I'm upgrading to the latest version (v7.0.8)

After upgrading, the call to `GetTokenAsync` - to get tokens by exchanging authorization code - kept failing with error message IDX10503 - Signature Validation Failed.

I cloned the repo and stepped through the code and noticed that the code which validates the ID Token uses the client secret as is without first replacing _ and - with / and +, respectively, causing the signature validation to fail. Replacing those characters before signature validation works.

I also tried replacing those characters in client secret passed to `GetTokenAsync` (through `AuthorizationCodeTokenRequest`). It failed with Unauthorized error when calling `oauth/token` endpoint.

### Reproduction
This issue can be consistently reproduced when calling `GetTokenAsync` of `AuthenticationApiClient` when JWT signing algorithm is HS256 and client secret contains _ or -

### Environment
- **Version of this library used:** 7.0.8
- **Version of the platform or framework used, if applicable:** .NET v4.6.1

**Comment by frederikprijck** [comment]
Hi @shri-aithal ,

I am unable to reproduce the issue. 

I am using `HS265` and a ClientSecret that contains multiple `_` characters.
Calling `GetTokenAsync` with an instance of `AuthorizationCodeTokenRequest`, containing the retrieved `code` as well as the ClientId, ClientSecret, RedirectUri and SigningAlgorithm results in the succesful retrieval of a Token.

Would you be able to provide a little more details so that I can try and reproduce this?

**Comment by shri-aithal** [comment]
Hi @frederikprijck ,

I've been using a modified version of the source code ever since I encountered the problem. Specifically, I changed the constructor of `auth0.net/src/Auth0.AuthenticationApi/Tokens/SymmetricSignedDecoder.cs`

Before:
```
public SymmetricSignedDecoder(string clientSecret)
    : base(JwtSignatureAlgorithm.HS256, new [] { new SymmetricSecurityKey(Encoding.ASCII.GetBytes(clientSecret)) })
```

After: 
```
public SymmetricSignedDecoder(string clientSecret)
    : base(JwtSignatureAlgorithm.HS256, new [] { new SymmetricSecurityKey(Utils.Base64UrlDecode(clientSecret)) })
```

After reading your comment, I switched back to the NuGet package to see if it works. However, I'm still seeing the same error as before. Here's the stack trace of the exception:

```
[SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.]
   System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) +2295
   System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken) +215
   Auth0.AuthenticationApi.Tokens.SignedDecoder.DecodeSignedToken(String token) +57

[IdTokenValidationException: Invalid token signature.]
   Auth0.AuthenticationApi.Tokens.SignedDecoder.DecodeSignedToken(String token) +191
   Auth0.AuthenticationApi.IdTokenValidator.DecodeSignedToken(IdTokenRequirements requirements, String idToken, String clientSecret) +82
   Auth0.AuthenticationApi.<Assert>d__3.MoveNext() +71
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Auth0.AuthenticationApi.<GetTokenAsync>d__14.MoveNext() +616
```

**Comment by frederikprijck** [comment]
@shri-aithal ,

Could u set this flag to true to get more log information?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.logging.identitymodeleventsource.showpii?view=azure-dotnet

Would u be able to provide a reproduction sample? That might speed things up for me to get it reproduced and fixed, as I cant get it reproduced on my end.

Thqnks

**Comment by shri-aithal** [comment]
@frederikprijck ,

Here's the first part of stack trace after enabling ShowPII flag

```
[SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: '72ac1374-dfcb-4b7a-aa23-cbe6a935dbba'. , KeyId: 
'.
Exceptions caught:
 ''.
token: '<ID Token JWT in plain text>'
```

> Would u be able to provide a reproduction sample? That might speed things up for me to get it reproduced and fixed, as I cant get it reproduced on my end.

Unfortunately, no. The code is part of a bigger project and difficult to extract out.

> As you are using Utils.Base64UrlDecode, is your clientSecret base64 encoded ?

Yes. The client secret is base64 encoded (as obtained from Application Settings page in Auth0 management site).

**Comment by frederikprijck** [comment]
Thanks for providing that info @shri-aithal .

It looks like previously, client secrets used to be base64 encoded. Now they are not anymore when u create a new application.

We will investigate this internally and I will get back to you.

Thanks for reporting this!

**Comment by frederikprijck** [comment]
Hi @shri-aithal ,

Some time ago, Auth0 switched from using Base64 encoded client secrets to using non-Base64 encoded client secrets.
Applications created before that time are still making use of encoded client secrets whereas new clients do not.

Apparently, our current .NET SDK does not support using Base64 encoded client secrets. 

However, Any old application can rotate their client secret to lose Base64 encoding as mentioned [here](https://community.auth0.com/t/rotating-my-client-secret-and-base64-encode/34072). You can achieve this through the Auth0 dashboard by going to your application settings and going into the Danger Zone at the bottom of the page:

![image](https://user-images.githubusercontent.com/2146903/95782943-2564e700-0cd1-11eb-9f87-cdb999cd3a27.png)

**Keep in mind, rotating your client secret will make the old secret stop functioning, meaning you will need to patch your application with the new client secret as soon as possible to limit the downtime of your application.**
 
Another idea could be to create a new Auth0 application and to migrate to that new application. This would ensure you are not using encoding and you can make the switch without downtime.

Given the fact that this is a legacy feature and the workaround available (patching the SDK the way you did as well as rotating the client secret to lose the encoding), we feel like we shouldn't update our SDK to support this natively.

Nevertheless, thank you very much for reporting this issue.
