### ISSUE TITLE
Issue specifying "upsert" for ImportUsersAsync

### ISSUE THREAD

**Issue by drjaydenm** [auth0/auth0.net#411]
### Description

When specifying the `upsert` parameter as `true` in the `ImportUsersAsync` method for the management API, it does not serialize correctly as Auth0 expects and instead comes out in the request as `True` (capital "T"). The Auth0 management API doesn't expect/handle this value and instead defaults `upsert` to `false`.

The only way we can bypass this at the moment seems to be not using this wrapper and going to HttpClient directly.

### Reproduction

```csharp
var jobResponse = await managementClient.Jobs.ImportUsersAsync(
                        connectionId: "con|1234",
                        fileName: "userdata.json",
                        file: stream,
                        upsert: true,
                        externalId: "123",
                        sendCompletionEmail: false);
```

### Environment

Latest Auth0.net library (7.0.8)

**Comment by drjaydenm** [comment]
@damieng Thanks for fixing this so quickly, any chance we could get a new release of the library with this change in it?

**Comment by lbalmaceda** [comment]
@drjaydenm should be ready in 7.0.9

**Comment by drjaydenm** [comment]
@lbalmaceda Thanks for getting that release out, I appreciate it!
