### ISSUE TITLE
Management API - Connections - GetAllAsync with multiple strategies

### ISSUE THREAD

**Issue by kerpekri** [auth0/auth0.net#416]
### Description

I am trying to call ManagementApiClient.Connections.GetAllAsync() method with multiple connection strategies specified.

### Reproduction

For example:
![image](https://user-images.githubusercontent.com/3390216/87534756-2325c900-c69f-11ea-92e7-b0365878548d.png)

but it fails with:
{
    "message": "An item with the same key has already been added. Key: strategy"
}

I already checked unit tests for this project, but I can't really understand how can I achieve that I don't need to make two different requests to get all Enterprise connections for samlp & adfs?

From documentation:
![image](https://user-images.githubusercontent.com/3390216/87535134-a9daa600-c69f-11ea-830d-12a4591c1471.png)

I can easily do that from Postman:
![image](https://user-images.githubusercontent.com/3390216/87535379-12c21e00-c6a0-11ea-8ef4-6ba5a8a9bee0.png)

### Environment

> Please provide the following:

- **Version of this library used:**
7.0.9 Auth & Management Api's
- **Version of the platform or framework used, if applicable:**
netcoreapp2.1
- **Other relevant versions (language, server software, OS, browser):**
C#
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Thanks for reporting this @kerpekri .
We have been able to reproduce this and we will look into fixing this.

**Comment by frederikprijck** [comment]
This should be fixed with version 7.2.0 that has just been released.
