### ISSUE TITLE
Session Lifetimes

### ISSUE THREAD

**Issue by stphnlwlsh** [auth0/auth0.net#418]
Not a bug necessarily, but I couldn't find the documentation on this, when updating fields, which fields trigger a session to expire server side?

Use case is I have a SPA using universal login with a dotnet core backend API. For users with user/pass logins, I'd like to keep their profile data up to date both in my app database as well as Auth0. When sending a request via `Users.UpdateAsync`, I couldn't quite pin down which fields I'm sending expire the server side session. I know that the session is expired because a page refresh on the SPA side indicates that the user is logged out.

Any guidance here? For now I'm sending an update request with the 4 or so fields I know do NOT expire the session (the name fields: first, last, nick, full).

**Comment by damieng** [comment]
There is nothing specific in the auth0.net SDK that would cause the invalidation - I would assume if this is happening it would be something upstream on the server side. If you can't find any docs about that online then you might want to ask on the community forums at https://community.auth0.com/ as to what fields when updated cause a session invalidation.

**Comment by stphnlwlsh** [comment]
Thanks @damieng I assumed it was something server side at Auth0 as a result of the management API being called internally, but I'll post the question in the community as well and close this out.
