### ISSUE TITLE
Support Passwordless Authentication

### ISSUE THREAD

**Issue by sam-piper** [auth0/auth0.net#419]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

At the moment we can use `AuthenticationApiClient` to send an OTP to an email or mobile number, via `StartPasswordlessEmailFlowAsync()` or `StartPasswordlessSmsFlowAsync()`, which is straight-forward, however, there doesn't appear to be any way to authenticate a code using the client's current API. 

### Describe the ideal solution 

Ideally, there would be an overload of `GetTokenAsync()` that takes a request type specific to the passwordless authentication flow (https://auth0.com/docs/api/authentication#authenticate-user) and implementation that can call the Authentication API endpoint and return the relevant response types, similar to the existing overloads of this method.

## Alternatives and current work-arounds

Currently, we have to use `HttpClient` manually to invoke this endpoint, which is fine, but it would be nicer to have this provided as part of the SDK as well, as that would be much simpler code and easier to maintain.

**Comment by frederikprijck** [comment]
Hi @sam-piper,

Thanks for reporting this and sorry for the delayed response!
Using a GetTokenAsync overlay for this specific use case doesn't sound like a bad idea.

I will check this internally and get back to you.

**Comment by frederikprijck** [comment]
This is now available as part of the latest (`7.3.0`) release.
