### ISSUE TITLE
Provide public helpers to decode and validate jwt tokens

### ISSUE THREAD

**Issue by lnaie** [auth0/auth0.net#421]
Hello,

I checked the code to see how token decoding and validation was implemented. It's all there but internal.
The reasoning is that I'm already using this library, why should I use another one for the same job?! :)

Is it possible to make some of that code public via some helpers?

Thanks

**Comment by frederikprijck** [comment]
Hi @lnaie,

Sorry for the late response. would you be able to use `System.IdentityModel.Tokens.Jwt`, a nuget package provided by Microsoft to handle this? 

Here are some relevant links:
https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler?view=azure-dotnet
https://stackoverflow.com/questions/18677837/decoding-and-verifying-jwt-token-using-system-identitymodel-tokens-jwt
https://www.jerriepelser.com/blog/manually-validating-rs256-jwt-dotnet/

Let me know if this doesnt help,
