### ISSUE TITLE
Support additional fields in 

### ISSUE THREAD

**Issue by assafsl** [auth0/auth0.net#427]
The `CreateCustomerRequest`, `UserUpdateRequest` classes provide only a subset of the fields supported by the API (as shown here: https://auth0.com/docs/api/management/v2#!/Users/post_users).

It would be great to be able and set given_name, family_name etc. using the SDK.

**Comment by frederikprijck** [comment]
Hi @assafsl ,

The fields you mention are available as part of the SDK, they are part of the UserBase class, which both UserCreateRequest and UserUpdateRequest inherit.

https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/UserCreateRequest.cs#L8
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/UserUpdateRequest.cs#L8
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/UserBase.cs
