### ISSUE TITLE
Getting "The resource server does not exist" when Assigning permissions to the role in .NET5

### ISSUE THREAD

**Issue by dmitry-pavlov** [auth0/auth0.net#444]
* **Which SDK this is regarding:** NuGet Auth0.ManagementApi 7.1.0
* **SDK Version:** 7.1.0
* **Platform Version:** .NET 5 
* **Code Snippets/Error Messages/Supporting Details/Screenshots:** 

We are getting Auth0.Core.Exceptions.ErrorApiException: The resource server does not exist: "our-API-ID-value"

```
    ManagementApiClient client = new ManagementApiClient(token, uri, _connection); // where _connection is IManagementConnection
    string roleId = ...; // retrieved from Auth0 via client.Roles.GetAllAsync(new GetRolesRequest { NameFilter = role });
    string apiAid = _settings.ApiId; // valid API ID which is successfully used for retrieving roles.

    string[] permissions = new [] { "some:role:1", "some:role:2" }

    await client.Roles.AssignPermissionsAsync(roleId, new AssignPermissionsRequest // this line failes with the above error
    {
    	Permissions = permissions.Select(x => new PermissionIdentity { Identifier = apiId, Name = x }).ToList()
    });

```

**Comment by dmitry-pavlov** [comment]
Link to community thread as well: https://community.auth0.com/t/getting-the-resource-server-does-not-exist-when-assigning-permissions-to-the-role-in-net/52684

**Comment by frederikprijck** [comment]
Thanks for reporting the issue.

We currently have no official .NET 5 support yet. However, we would love to look into what it takes for us to do support it.
Would you be able to provide a small reproduction example so we can investigate the issue you are experiencing?

Thanks.

**Comment by dmitry-pavlov** [comment]
The same for .NET Core 3.1. By the way, we have added a support ticket for this #00470976 @frederikprijck

**Comment by dmitry-pavlov** [comment]
@konradsopala adding you here as well

**Comment by frederikprijck** [comment]
I just tried it using our SDK on .NET Core 3.1 and I am unable to reproduce this.
I was able to succesfully assign a permission to a role by copying your code and changing my token, apiId, roleId and permissions to match my tenant.

Can you verify that the API ID exists and that the token that is being used has permission to access that?

Keep in kind that support tickets are not handled through Github.

**Comment by dmitry-pavlov** [comment]
I confirm that API ID (value like 5f90767b32c58f0044a9301b) is what I see in Permission.Identifier property of existing permissions when I get them for thee role via : 

`var existing = await client.Roles.GetPermissionsAsync(roleId, new PaginationInfo()); `

Then I do this: 

 await client.Roles.AssignPermissionsAsync(roleId, new AssignPermissionsRequest
            {
                Permissions = new List<Permission> { new PermissionIdentity { Identifier = "5f90767b32c58f0044a9301b", Name = x }) } 
            });

which causes the error. 

@frederikprijck  for API https://manage.auth0.com/dashboard/eu/xenioss/apis/5f90767b32c58f0044a9301b/settings - what should be passed as API ID to AssignPermissionsAsync? 5f90767b32c58f0044a9301b or URI is API Audience?

**Comment by frederikprijck** [comment]
When I sent the API Identifier (not Id), which you can find in the Dashboard settings for your API, it works fine for me.

![image](https://user-images.githubusercontent.com/2146903/98287115-325db900-1fa5-11eb-9a63-c3e7e9e86cca.png)

**Comment by dmitry-pavlov** [comment]
I see, got it, thanks @frederikprijck !
