### ISSUE TITLE
Configure Refresh Token Rotation when creating a new Auth0 client.

### ISSUE THREAD

**Issue by SamTheWizard** [auth0/auth0.net#450]
Hello there
I need to create a new Auth0 client with the right configurations for refresh token rotation. The configurations i need are described here: https://auth0.com/docs/tokens/refresh-tokens/configure-refresh-token-rotation

Now i see that there is a property on the ClientCreateRequest model to set the OIDC conformant flag, which is the first thing i need to configure.

But at the moment i don't see a possibility to set the refresh token behaviour to "rotating" and to configure the refresh token lifetime.

I am new to using this library, so i might just be blind. But shouldn't there be some sort of "RefreshTokenConfiguration" property on the ClientCreateRequest and ClientUpdateRequest models?

**Comment by frederikprijck** [comment]
Thanks for reporting.
Currently, the SDK does not provide ways to populate the refresh token options when creating a client.

I think it would be a good addition to the SDK, we will discuss this internally and I will get back to you.

**Comment by Freeze8** [comment]
I'm currently also facing this problem as I switched from auth0-js to auth0-spa-js and want to configure the refresh token rotation. Looking forward to a solution as soon as possible

**Comment by SamTheWizard** [comment]
Hello again
Because this issue is really important to me, i tried to fix it and createt a PR.
I think this simple modle change should fix the problem.https://github.com/auth0/auth0.net/pull/451

**Comment by frederikprijck** [comment]
Fixed by https://github.com/auth0/auth0.net/pull/451

**Comment by frederikprijck** [comment]
Released in `7.3.2`

**Comment by jonasaebersold** [comment]
It only took about seven hours from the new reported issue to the finished nuget package. It is not my expectation that it always goes that fast. This message is just an appreciation, it's very impressive! Thank you very much for the quick and great support.

**Comment by frederikprijck** [comment]
Thanks for the appreciation here @jonasaebersold. It will definetly not always go that fast, however a lot of thanks goes to @SamTheWizard as he did amazing work on providing a fast and quality PR making it easy to get this in.
