### ISSUE TITLE
GetUsersRequest not filtering by Connection

### ISSUE THREAD

**Issue by connorconway** [auth0/auth0.net#466]
### Describe the problem

The following code is returning all users from all connections, and not filtering on the "Test" connection.

```
var users = ManagementApiClient.Users.GetAllAsync(new GetUsersRequest
{
        Connection = "Test"
        SearchEngine = "v3",
},
new PaginationInfo());
```

### What was the expected behaviour?

To return only the users that exist in the "Test" connection.
Our workaround is to add the following code to ensure that only the users from the "Test" connection are returned.

```
 var usersFromConnection = users.Where(u => 
   u.Identities.First().Connection.Equals("Test", StringComparison.OrdinalIgnoreCase));
```

However, we don't really want to be returning users from other connections at all from Auth0, and then filtering them client side.

### Environment

- **Version of this library used:** 7.5.0
- **Which framework are you using, if applicable:** .Net Core 2.1

**Comment by frederikprijck** [comment]
Hey, This behavior is expected, as the docs for this API mention that the `Connection` is only taken into account when using `SearchEngine=v1`: https://auth0.com/docs/api/management/v2#!/Users/get_users

![image](https://user-images.githubusercontent.com/2146903/106431858-27180d80-646e-11eb-94de-f483eea65c27.png)

Based on the docs, when using `SearchEngine v3`, you want to filter on Connections using the `Query` property on `GetUsersRequest`.

Let me know if that doesn't solve it for you.

**Comment by connorconway** [comment]
That has worked now. Appreciate the reply. Thanks!
