### ISSUE TITLE
Support Hooks API

### ISSUE THREAD

**Issue by connorconway** [auth0/auth0.net#470]
### Describe the problem you'd like to have solved

We currently deploy and manage a number of Hooks but this functionality does not seem to exist within this .net API.
https://auth0.com/docs/api/management/v2#!/Hooks/get_hooks

### Describe the ideal solution

To support /hooks endpoints (POST/PATCH/DELETE/GET).

### Additional information, if any

I've forked the repository and implemented a solution to this that we are using. I can raise a PR if that seems appropriate to you.

**Comment by frederikprijck** [comment]
Hi @connorconway,

PR's are always welcomed, so feel free to raise one if you'd like!

Thanks 🚀

**Comment by frederikprijck** [comment]
Released as part of 7.6.0
