### ISSUE TITLE
Management API Token Generation

### ISSUE THREAD

**Issue by mindingdata** [auth0/auth0.net#478]
### Describe the problem you'd like to have solved

Based on this thread here : https://github.com/auth0/auth0.net/issues/179

And on a similar vein. To use the ManagementAPI, one needs a token, where do you get the token from? Well, you have to make a request to Auth0 via the API, but the SDK does not provide a way to do this... So.. You are stuck. 

To me it's a no brainer that an SDK would have the ability to request a management token. I'm not too worried about the management of said token, and how often it gets refreshed, but to have to spin up our own HttpClient and make a JSON API request to the same API we will be calling within the SDK, but can't do through the SDK, is frustrating to say the least. 

And I just want to touch on some replies from Auth0 in the above thread. 

1. The solution given does not work. A hard coded token only lasts for 24 hours. 
2. Every single person that uses the management API will be copy and pasting the same Gist. It's not an "optional" thing that the SDK could or could not provide. Every single time someone uses this API, they have to find a work around to generate a management token. 

### Describe the ideal solution

The SDK should have a method to generate a management token, similar to this gist https://gist.github.com/finsterdexter/5e74b3bd4af8052ae6da4850af5e2124

## Alternatives and current work-arounds

At the moment, people are sharing their own github pastes etc and helping the community which is great to see, but it makes no sense for this to not be included in the SDK.

**Comment by frederikprijck** [comment]
Hey @mindingdata ,

What do you mean with this SDK does not contain methods to request Access Tokens?

We have 2 SDKs inside this repository:

- ManagementAPI: Used to handle calls to the Management API
- AuthenticationAPI: Used to get tokens using all kinds of grant types for any Audience, including the Management API.

Not always is it required to combine the two, but in your case it looks like what you want is this:

```
using(var authClient = new AuthenticationApiClient(Configuration["Auth0:Domain"])) 
{
  var token = await _authClient.GetTokenAsync(new ClientCredentialsTokenRequest
  {
      Audience = $"https://{Configuration["Auth0:Domain"]}/api/v2/",
      ClientId = Configuration["Auth0:ClientId"],
      ClientSecret = Configuration["Auth0:ClientSecret"]
  });
  using(var mgmntClient = new ManagementApi.ManagementApiClient(token.AccessToken, Configuration["Auth0:Domain"])) 
  {
     // use mgmntClient here
  }
}
```

We have a working example here: https://github.com/auth0/auth0.net/blob/master/playground/Auth0.NET5/Controllers/ClientsController.cs

> The SDK should have a method to generate a management token, similar to this gist

At the moment we are working on investigating how we can improve the SDK in this matter, as I believe I would love for the developer to avoid worrying about the token all together, and use an API like this:

```
using(var mngmntClient = new ManagementApiClient(Configuration["Auth0:ClientId"], Configuration["Auth0:ClientSecret"], Configuration["Auth0:Domain"]))
{
    var clients = await mgmntClient.Clients.GetAllAsync(new GetClientsRequest(), new ManagementApi.Paging.PaginationInfo());
}
```

However, today this is not possible and there is no timeframe yet on this. 
However, I believe there is no need for anyone to spin up their own HttpClient, it is just a matter of combining two SDKs, each having their own concern.

**Comment by mindingdata** [comment]
Interesting, I'll have a look at this. 

If I didn't create this ticket, how would I know about this? The documentation on Auth0 specifically gives code to use HttpClient, and coming here and searching "Management Token" in this repo brings up the issues that I mentioned. Maybe it might be worth while going back to those issues where there are comments to the effect that the SDK does not create tokens for you, and mentioning your comment above?

**Comment by frederikprijck** [comment]
@mindingdata I do not disagree that we could do better in terms of documenting this.
As we are currently investigating a bit of a rework on that side, I will ensure we either update the docs once we implement the changes or will address the docs if we decide not to make those changes.

I will add something to our backlog to track this.
