### ISSUE TITLE
Support For TLS Version 1.2

### ISSUE THREAD

**Issue by kler** [auth0/auth0.net#481]
From 2021-03-22 Auth0 will be requiring TLS 1.2.

- Does this package support that?
- If yes, from what version is TLS 1.2 supported? _(i.e., who will need to upgrade)_

See
- https://support.auth0.com/notifications/60075b84581057000b4a6739
- https://github.com/auth0/node-auth0/issues/581
- https://github.com/auth0/auth0-PHP/issues/479
- https://github.com/auth0/auth0-java/issues/337

**Comment by frederikprijck** [comment]
This library should work fine with TLS, as long as the version of .NET you are using is compatible with TLS 1.2.

If you are still on a .NET framework version that doesn't support TLS 1.2, you might need to update them, see https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client
