### ISSUE TITLE
non-paged requests?

### ISSUE THREAD

**Issue by aschwartz-satcom** [auth0/auth0.net#495]
Is it possible to make non-paged requests with this library?  Many of the Auth0 Management API endpoints support unpaged results, essentially by default.

**Comment by frederikprijck** [comment]
Thanks for reporting this and I believe you are entirely right, it is not supported for most of the API's that you try to call through this SDK.

I have added something to our internal backlog to get this resolved. Just to be clear, the priority around that isn't really high, given the fact you should be able to work around that yourself.

Nevertheless we believe it's a valid issue being raised here and happy to look into it.

In the case you have a strong need for this, do know we are always happy to look at a PR that allows for this.

**Comment by aschwartz-satcom** [comment]
Thanks - I did implement a workaround in my code, just thought it was an odd limitation and maybe I was missing something.

**Comment by Vitupero** [comment]
> Thanks - I did implement a workaround in my code, just thought it was an odd limitation and maybe I was missing something.

How did you override this? I haven't tried to do this before.
