### ISSUE TITLE
UserCreateRequest model password property XML documentation change

### ISSUE THREAD

**Issue by Goolyio** [auth0/auth0.net#496]
### Describe the problem
[The UserCreateRequest XML documentation](https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/UserCreateRequest.cs#L23) is missing the email connection type from the summary as it is also non manditory. It currently says:

> Gets or sets the user's password. This is mandatory on non-SMS connections.

But the password property is also not manditory on email connections. My suggestion is to change it to:

> Gets or sets the user's password. This is mandatory on non SMS or email connections.

PR: #497 

Please let me know if you think it could be reworded better :)

**Comment by frederikprijck** [comment]
Hey,

Thanks for reaching out.

This documentation comes straight from the API documentation: https://auth0.com/docs/api/management/v2#!/Users/post_users

Where possible we try to stick to the docs from the API in terms of property description.

So let me have a conversation internally to see why this is inaccurate.

Thanks

**Comment by frederikprijck** [comment]
Hey @Goolyio ,

I have raised this with the corresponding team internally and they agree it's incorrect.
They are going to look into updating the API docs.

Once that is done we can align our documentation with the API docs.

I am not going to review your open PR before they have made that change, but know that I am keeping an eye on it and will review it once the API docs are merged.

Thanks again for reporting this, very much appreciated! 🚀

**Comment by Goolyio** [comment]
Hey @frederikprijck,

Sounds like a good plan! Looking forward to seeing what the updated documentation will look like, was struggling to think of a nice way to write it.

Cheers for the fast responses and updates 😄

**Comment by frederikprijck** [comment]
There hasn't been any change on the docs side, I will check internally what the plan is for that. 
Sorry for the delay, but as I mention our docs follow the official API docs.

**Comment by Goolyio** [comment]
No worries, I imagine its not a high priority issue 😉
