### ISSUE TITLE
Support HttpClient factory with AddHttpClient<> or from the constructor 

### ISSUE THREAD

**Issue by pilouk** [auth0/auth0.net#498]
### Describe the problem you'd like to have solved
I try to use the built in .net HttpFactory  _AddHttpClient_ provider, since there is no httpclient provided in the constructor obviously this doesn't work.

I also try to use the HttpFactory like so without success:
_services.AddScoped<IAuthenticationApiClient, AuthenticationApiClient>(s =>
            new AuthenticationApiClient(Configuration["Auth0:AuthAPI:Domain"],
            new HttpClientAuthenticationConnection(s.GetService\<IHttpClientFactory\>().CreateClient())));_

### Describe the ideal solution
AddHttpClient should work fine or atleast a way to use the http factory pattern.

## Alternatives and current work-arounds
Is there anyway i can use the http factory pattern with your library ?

**Comment by frederikprijck** [comment]
Hey @pilouk,

This library doesn't do anything regarding Dependency Injection or its registration. Therefore this is totally up to you.

```
services.AddScoped<IAuthenticationApiClient, AuthenticationApiClient>(s =>
new AuthenticationApiClient(Configuration["Auth0:AuthAPI:Domain"],
new HttpClientAuthenticationConnection(s.GetService<IHttpClientFactory>().CreateClient())));
```

I would expect this to work. Any chance you can share a sample that shows this doesn't work?  Happy to help looking into it. 

But as I said, as this library doesn't do anything with regards to DI, I believe this should work and the issue might be somewhere else.

**Comment by pilouk** [comment]
> Hey @pilouk,
> 
> This library doesn't do anything regarding Dependency Injection or its registration. Therefore this is totally up to you.
> 
> ```
> services.AddScoped<IAuthenticationApiClient, AuthenticationApiClient>(s =>
> new AuthenticationApiClient(Configuration["Auth0:AuthAPI:Domain"],
> new HttpClientAuthenticationConnection(s.GetService<IHttpClientFactory>().CreateClient())));
> ```
> 
> I would expect this to work. Any chance you can share a sample that shows this doesn't work? Happy to help looking into it.
> 
> But as I said, as this library doesn't do anything with regards to DI, I believe this should work and the issue might be somewhere else.
> 
> This probably also is an interesting thread that is tangibly related: #179

Yeah it's worked fine, this was on my end !
