### ISSUE TITLE
Enrollment feature beside guardian (MFA API)

### ISSUE THREAD

**Issue by pilouk** [auth0/auth0.net#499]
### Describe the problem you'd like to have solved
Is it possible to enroll user beside Guardian with this sdk ? Like SMS/Voice or email ?
I don't see any implementation beside the Guardian MFA and GetEnrollmentAsync().

### Describe the ideal solution

Have the MFA API included in this sdk
Be able to enroll user to SMS, Email etc.. MFA
Be able to confirm the enrollment to get an access token

**Comment by frederikprijck** [comment]
Thanks for reaching out.

This currently is not possible. This does sound like something we would be willing to add, but isn't something that will be a top priority.

If you have a strong need for this, happy to look into reviewing a PR if you are willing to create a PR.

**Comment by frederikprijck** [comment]
We have no direct plans to add this. If you have any need for these endpoints, we are happy to look into a PR, closing for now but feel free to continue the conversation and we can reopen if needed.
