### ISSUE TITLE
Update Asyncs API to take CancellatiionToken

### ISSUE THREAD

**Issue by Socolin** [auth0/auth0.net#500]
Hello,

All the Async methods inside `IAuthenticationApiClient`  are not taking any CancellationToken, it would be nice, this would allow to be able to set timeout, or to cancel requests if the users cancelled the request in ASP.NET Core while it's waiting for a response from auth0 API.

More details can be found here

https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken/

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Out of curiosity, what methods of this SDK are you using in ASP.NET Core?

**Comment by Socolin** [comment]
I'm using

`Task<AccessTokenResponse> GetTokenAsync(ClientCredentialsTokenRequest request);`

**Comment by frederikprijck** [comment]
Thanks, that makes sense!

I believe requesting support for CancellationToken makes sense as well, thanks for that.

Marking this as `Help Wanted` for now, as we cant prioritize this on the short term.
If you want to, feel free to open a PR and I am happy to review. If not, we will look into this later!
