### ISSUE TITLE
Cannot use grant type password realm

### ISSUE THREAD

**Issue by scott-david-walker** [auth0/auth0.net#501]
Trying to retrieve a token for a use and retrieving a password grant error.

"Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client."

My app is setup to use the password grant and I'm connecting via:

`var t = await auth.GetTokenAsync(new ResourceOwnerTokenRequest
            {
                ClientId = "Id",
                ClientSecret = "secret",
                Username = "email",
                Password = "password",
                Realm = "Username-Password-Authentication"
            });`

The realm is the default database connection that was available on creation of the app.

I've browsed the docs but all the solutions seem specific to enabling the password grant which I've already done.

Any ideas?

**Comment by frederikprijck** [comment]
Hey,

This error sounds like an error unrelated to the SDK being used, can u please verify the same error exists if you execute the call to retrieve a token using cURL, Postman or any comparable tool that doesn't use our SDK?

If the error does not occur in the case of using cURL or Postman, please let me know so we can see what is different with using our SDK.

Could u also show how you enabled the Password grant and can you verify that it's enabled for the correct client in your Auth0 dashboard?

Thanks.

**Comment by scott-david-walker** [comment]
The issue was that I didn't have a default directory setup as a part of the tenant settings.

![image](https://user-images.githubusercontent.com/13588473/120312737-01422e80-c2d1-11eb-8057-cf968915a7e1.png)
