### ISSUE TITLE
Missing field in OrganizationConnection

### ISSUE THREAD

**Issue by nickroyerUBC** [auth0/auth0.net#502]
When running the api in postman for the endpoint:

https://{{auth0_domain}}/api/v2/organizations/Org_ID/enabled_connections

it returns: 
    {
        "connection_id": "abc",
        "assign_membership_on_login": false,
        "connection": {
            "name": "test",
            "strategy": "abcde"
        }
    }

however the "connection" object is missing in the SDK (7.8.0)

    public class OrganizationConnection
    {
        public OrganizationConnection();

        //
        // Summary:
        //     ID of the connection.
        [JsonProperty("connection_id")]
        public string ConnectionId { get; set; }
        //
        // Summary:
        //     Whether or not users that login will automatically be granted membership to the
        //     organization.
        [JsonProperty("assign_membership_on_login")]
        public bool AssignMembershipOnLogin { get; set; }
    }

the root cause of why this is important is because for some reason the user.Identities only contains the name of the connection and not connection id

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by frederikprijck** [comment]
Thanks for reporting, this field looks to be missing indeed but needs to a bit more work to get this resolved as we are currently using this same class also when creating and updating the connections.
