### ISSUE TITLE
Encoding issue when username has "+"

### ISSUE THREAD

**Issue by ntotten** [auth0/auth0.net#51]
If string username has a "+" in it, the NestSharp Library method ParameterType.GetOrPost url encodes the "+" as %2B

It would appear that /oauth/ro converts %2B to single spaces ' ' in the username of the account created.

/oauth/ro has no problem creating accounts with usernames containing "+" signs... it's the url encoding of the username that causes the issue.

You can find the code here: https://github.com/auth0/auth0.net/blob/master/Auth0.Net/Client.cs

**Comment by jerriep** [comment]
Tested with V2 and it works fine as parameters are passed in body as JSON instead of being passed as query string parameters.
