### ISSUE TITLE
Support checkpoint pagination

### ISSUE THREAD

**Issue by AndreasHae** [auth0/auth0.net#510]
### Describe the problem you'd like to have solved

I'm using the management API to query members of an organization and I need to use checkpoint pagination for my use-case. As documented in the [API explorer]
(https://auth0.com/docs/api/management/v2#!/Organizations/get_members), I can use either offset pagination (provide a page no. and page size) or checkpoint pagination (providing a starting ID and amount of users to retrieve after this). The latter is necessary if you want to retrieve more than 1000 users.

Browsing the auth0.net API, I did not find a way to use checkpoint pagination.

### Describe the ideal solution

Provide a means to use checkpoint pagination endpoints in the library.

### Alternatives and current work-arounds

For now I will write my own API client class.

**Comment by frederikprijck** [comment]
There is a PR open for this: https://github.com/auth0/auth0.net/pull/507

**Comment by AndreasHae** [comment]
Nice, didn't see this. Thanks for the quick response! When do you expect this to be available?
