### ISSUE TITLE
Missing constructor public AuthenticationApiClient(IAuthenticationConnection connection)

### ISSUE THREAD

**Issue by rhyswilliamszip** [auth0/auth0.net#523]
### Describe the problem

The documentation states you can pass your own custom http client using the below constructor
``var client = new AuthenticationApiClient(new HttpClientAuthenticationConnection(myHttpClient));``

However the class only has two constructors either requiring base uri or domain

``public AuthenticationApiClient(Uri baseUri, IAuthenticationConnection connection = null)``

``public AuthenticationApiClient(string domain, IAuthenticationConnection connection = null)``

### What was the expected behavior?

Class should have a constructor described in the documentation.

[http://auth0.github.io/auth0.net/api/Auth0.AuthenticationApi.AuthenticationApiClient.html]()

It doesn't make sense to provide a domain or baseUri when supplying a http client as the base address will be specified in the client itself.

### Reproduction

Issue with documentation/code .

### Environment

All

**Comment by rhyswilliamszip** [comment]
Noticed method is in the constructor.

**Comment by frederikprijck** [comment]
Thanks for bringing that up!

> It doesn't make sense to provide a domain or baseUri when supplying a http client as the base address will be specified in the client itself.

This is incorrect, as the baseUri is used inside `AuthenticationApiClient`, and not inside the HttpClient, see https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs.

I believe the fix here should be to update the docs to also include the `baseUri` in the snippet.

Happy to look at any PR if you can provide one.

**Comment by rhyswilliamszip** [comment]
No problem makes sense.

Cheers
