### ISSUE TITLE
Management API - Keys Endpoints

### ISSUE THREAD

**Issue by colinbobolin** [auth0/auth0.net#526]
### Describe the problem you'd like to have solved

I need to access the [signing keys](https://auth0.com/docs/api/management/v2/#!/Keys/get_signing_keys) endpoints of the management API.

### Describe the ideal solution

The .NET SDK includes the Keys endpoints

## Alternatives and current work-arounds

Do not use the SDK. Implement API calls using some other HTTP client library.

### Additional information, if any

Maybe I missed this endpoint somewhere else in the documentation, but I would expect to see `.Keys` available in the `ManagementApiClient` properties.

**Comment by frederikprijck** [comment]
Thanks for reporting, these endpoints are currently not implemented in this SDK.
Happy to look at a PR if you can provide one.

**Comment by colinbobolin** [comment]
I might work on a PR for this. Let me know.
