### ISSUE TITLE
Management API Update SMS/Voice

### ISSUE THREAD

**Issue by chrisfink** [auth0/auth0.net#528]
Currently the Management API does not appear to have any functionality to update the MFA phone message delivery method SMS and SMS and Voice options.  This request is to add that functionality to the Management API.

Per the Auth0 documentation (https://auth0.com/docs/login/mfa/mfa-factors/configure-sms-voice-notifications-mfa) it states that I can do this manually currently but I would prefer to to this via the Management API nuget package if possible.

var client = new RestClient("https://YOUR_DOMAIN/api/v2/guardian/factors/phone/message-types");
var request = new RestRequest(Method.PUT);
request.AddHeader("content-type", "application/json");
request.AddHeader("authorization", "Bearer MGMT_API_ACCESS_TOKEN");
request.AddParameter("application/json", "{ \"message_types\": [\"sms\", \"voice\"] }", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);

Thank you

**Comment by frederikprijck** [comment]
Thanks for reaching out and sorry for the delay.
I will look into this anytime soon to see how and if we should support this.
