### ISSUE TITLE
Guardian.UpdateFactorAsync not working for most factors

### ISSUE THREAD

**Issue by leemcmullen** [auth0/auth0.net#534]
### Describe the problem

Calling `ManagementApiClient.Guardian.UpdateFactorAsync` only ever updates `push-notification` or `sms` factors. If `push-notification` is sent in the request, it is updated ok. Otherwise, it always updates `sms` irrespective of which value is passed.

I believe it's being caused by this line:
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/GuardianClient.cs#L130

### What was the expected behavior?

Expected behaviour is to update the factor which was passed in the request.

### Reproduction
- Ensure OTP and SMS factors are disabled in your Auth0 dashboard
- Make a call to update the OTP factor e.g.
```
var auth0 = new ManagementApiClient(auth0Token, ManagementApiUri);
var mfaFactorUpdatedResponse = await auth0.Guardian.UpdateFactorAsync(new UpdateGuardianFactorRequest {
    Factor = GuardianFactorName.Otp,
    IsEnabled = true
  });
```
- Refresh your Auth0 dashboard. SMS will now be enabled. OTP won't be enabled.

### Environment

- **Version of this library used: 7.11.0**
- **Which framework are you using, if applicable: net5.0**
- **Other modules/plugins/libraries that might be involved: No**
- **Any other relevant information you think would be useful:**

**Comment by frederikprijck** [comment]
Thanks, I added a PR to address this.

**Comment by leemcmullen** [comment]
Thanks for looking into this, @frederikprijck. Just added a comment to your PR: https://github.com/auth0/auth0.net/pull/536/commits/2d4102ef796a5fa2a993777d718b72c70ba027de#r753157314

I'm not _that_ familiar with the lib but using `var name = request.Factor.ToEnumString();` worked when I span things up locally so thought it was worth mentioning 👍

**Comment by frederikprijck** [comment]
Yeah I missed that method 🤦 , thanks!

**Comment by leemcmullen** [comment]
No worries at all, happy to help 👍

Thanks again for taking a look 😊

**Comment by frederikprijck** [comment]
Fixed, will be part of the next release.
