### ISSUE TITLE
CreateAsync - cannot prevent email from being sent  

### ISSUE THREAD

**Issue by tandreasen** [auth0/auth0.net#535]
I am using the auth0.net management API and am having a bit of trouble: I want to create a user, but it seems like this code is sending a password reset invitation:

```
      var management = new ManagementApiClient(token, _auth0Uri.Host, _managementConnectionService);


            var request = new UserCreateRequest
            {
                Email = nppUser.Email,
                FirstName = nppUser.FirstName,
                LastName = nppUser.LastName,        
                Password = Guid.NewGuid().ToString(),
                Connection = ConnectionName,
                VerifyEmail=false
            };
```
According to this and this I can set VerifyEmail to false and it should not send an email, but it is anyways. I’ve also tried EmailVerified=false and it yields the same result. I am doing this because I need to customize the invitation process, and showing “Reset Password” isn’t exactly the most thoughtful invitation (and I still want to use the reset password email for actual email resets). Thanks.

- **Version of this library used:** Auth0.ManagementApi 7.12.0
- **Which framework are you using, if applicable:** .NET 5.0 
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment]
Hey,

Thanks for reporting this.
Can u verify if this behavior is different when u call the API using something like Postman or CURL directly?

Thanks,

**Comment by tandreasen** [comment]
Hi, 

Thanks for following up - I found out that somebody had created a hook that was causing this behavior.  I confirmed that this is not an issue with auth0.net - please close this issue.  

Thanks for your time.
