### ISSUE TITLE
support for dotnet maui

### ISSUE THREAD

**Issue by HobDev** [auth0/auth0.net#537]
I am currently using Auth0 in a Xamarin.Forms app. The Maui App development framework is in preview. Maui will be GA(Generally Available) around April, 2022. It is a evolution of Xamarin.Forms.
All of the Xamarin.Forms apps will be converted to Maui as Microsoft has stopped new development on Xamarin.Forms. 
Thus Auth0 should be compatible with Maui at the earliest. This will allow the developers to test their apps before hand.

**Comment by frederikprijck** [comment]
Thanks for reaching out, this SDK has nothing to do with Xamarin.
For Xamarin application we have this SDK: https://github.com/auth0/auth0-oidc-client-net

That said, we do have MAUI on our radar and will evaluate once MAUI has been released in GA.
