### ISSUE TITLE
ManagementApi does not include a client for Rules Configs

### ISSUE THREAD

**Issue by caldwell0414** [auth0/auth0.net#551]
### Describe the problem you'd like to have solved

We make use of the ManangementApi to automate configuration of our tenants.  This includes managing rules.  We are unable to set config variables because there is no client in the API to call the /rules-configs endpoints on the Auth0 v2 management API.

### Describe the ideal solution

We will provide a PR that implements a RulesConfigClient that follows the pattern of other clients and includes the cleanup work done by @frederikprijck in the chore/test-cleanup branch.  We recommend that you accept his PR prior to accepting ours.

We appreciate the opportunity to contribute to this library.

## Alternatives and current work-arounds

The only current work around is to use an HTTP client and make direct PUT and DELETE requests to the v2 Management API endpoints.

### Additional information, if any

For security reasons, rules configuration variables cannot be read from the API, so there is no GET implementation in our PR.  We confirm through unit tests that the CreateOrUpdateAsync() calls will either create or overwrite existing configuration variables.

Finally, it is important to note that the default scopes generated for the Management API client do not include rules-configs:delete, so customers will have to add this scope in order to use the DeleteAsync() method call.  We confirmed that the API correctly returns the 403, along with a message indicating the missing scope when it is not present.

**Comment by frederikprijck** [comment]
Will be included in the next release, thanks for the PR!

**Comment by caldwell0414** [comment]
You are very welcome.

I apologize for being away this week and unable to make the changes you requested.  I appreciate your help in getting this PR merged!

jc
