### ISSUE TITLE
Set another ClientId (Application Name) on the Welcome Email after Users.CreateAsync()

### ISSUE THREAD

**Issue by elciopa** [auth0/auth0.net#557]
var auth0ManagementToken = await GetManagementToken();
            var managementApiClient = new ManagementApiClient(auth0ManagementToken, new Uri(auth0ManagementApiUrl));

### Describe the problem you'd like to have solved
Suppose I have several applications and for some reason I need to use the Auth Management API to create a user. 
```
var auth0ManagementToken = await GetManagementToken();
var managementApiClient = new ManagementApiClient(auth0ManagementToken, new Uri(auth0ManagementApiUrl));

var userCreateRequest = new UserCreateRequest
{
    "connection": "connection",
    "email": "emai@address.com",
    "email_verified": true,
    "verify_email": false,
    "password": "supersecret!!",
}
var createdUser = await managementApiClient.Users.CreateAsync(userCreateRequest, cancellationToken);
```
The "Welcome Email" is enabled in the Auth0 Tenant and once called the managementApiClient.Users.CreateAsync() the welcome email sent has the "application name" of the "Management Application" used for the M2M communication with the "Auth0 Management API"

### Describe the ideal solution
 It would be nice if the CreateAsync would be able to accept as input, another ClientId in order to better customize Email Templates.  In this way I would not recieve the email templates with the application name of the Application used for the M2M communication with "Auth0 Management API".

**Comment by frederikprijck** [comment]
It doesn't look like the API to create a user supports sending a client id. It uses the client based on the token provided to the ManagementApiClient, so there is not much we can do from the SDK side. See: https://auth0.com/docs/api/management/v2#!/Users/post_users

There may be ways to avoid the application name by customizing the email template, as mentioned in https://auth0.com/docs/customize/email/email-templates.

Closing this as there isn't much we can do from our SDK.

**Comment by elciopa** [comment]
Yes you are correct. It's something not feasible via APIs. 
Thanks for the reply.
