### ISSUE TITLE
Repo needs a "V2" milestone for issues

### ISSUE THREAD

**Issue by advancedrei** [auth0/auth0.net#56]
Would be nice if collaborators could tag issues with "v2" and statuses like "bug", "feature request", etc.

**Comment by jerriep** [comment]
@ntotten Can you please create this milestone?

Also, I would like to have access to the repo to be able to assign milestones and labels to issues, so I can get all the outstanding issues created and manage them.

**Comment by ntotten** [comment]
@jerriep I created the milestone and gave you write access so you can manage issues, etc.

**Comment by jerriep** [comment]
:+1:
