### ISSUE TITLE
Unable to access 'provisioning_ticket_url'

### ISSUE THREAD

**Issue by zzanol** [auth0/auth0.net#561]
Connection does not include property ProvisioningTicketUrl  (provisioning_ticket_url) so we're unable to display this URL in our UI.

Please add ProvisioningTicketUrl to the Connection model.

**Comment by frederikprijck** [comment]
Are you referring to the property that comes from Azure AD? 

If so, would you be able to provide a PR that adds support for that? I would be happy to review it and include it in the SDK!

**Comment by zzanol** [comment]
It's a URL that is generated by Auth0 (I believe) for authorizing Google Workspace enterprise connections.

In the Auth0 UI, this URL is found on the 'Setup' tab of a Google Workspace connection.

**Comment by zzanol** [comment]
PR submitted, https://github.com/auth0/auth0.net/pull/562/commits/e0fa901bc5bf3966dbd17be9d454463afd60fa89

**Comment by zzanol** [comment]
PR merged, https://github.com/auth0/auth0.net/commit/ba171f6ed0948c2d15cf0d54417443ec35840cd4
