### ISSUE TITLE
Unable to change the connection name for passwordless flow

### ISSUE THREAD

**Issue by jakubdrabik** [auth0/auth0.net#563]
### Describe the problem

Based on your documentation, it's possible to implement a custom SMS gateway for passwordless authentication, however, it's not possible to specify this connection by name in the `StartPasswordlessSmsFlowAsync` method, there is `sms` value directly instead. 

https://github.com/auth0/auth0.net/blob/f53f22e1c6fb95350fb427be878a980169227b51/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs#L390 

### What was the expected behavior?

I would expect this parameter being configurable from the outside as part of the `PasswordlessSmsRequest`.

**Comment by frederikprijck** [comment]
Could you elaborate what documentation you are referring to?
Based on the API docs, which this SDK calls, you can only specify `email` or `sms`, see : https://auth0.com/docs/api/authentication#get-code-or-link

**Comment by frederikprijck** [comment]
Closing as no response. Can always reopen if needed.
