### ISSUE TITLE
'Display_name' property missing on ConnectionCreateRequest 

### ISSUE THREAD

**Issue by rinkeb** [auth0/auth0.net#572]
According to [the docs](https://auth0.com/docs/authenticate/identity-providers/social-identity-providers/oauth2#modify-the-icon-and-display-name) it should be possible to set a display name on social connections via the Management api. 

However, neither the ConnectionCreateRequest or ConnectionUpdateRequest request object types have a corresponding property. 
I tried setting the value via the Options property, but that does not seem to work.

Could this be added please? 

Auth0.ManagementApi version: 7.16.0.0 (via nuget)

**Comment by frederikprijck** [comment]
Thanks for reaching out, it looks like this property is indeed missing.

We can definitely add it, also happy to review any PR if you want to open one.
