### ISSUE TITLE
IManagementApiClient

### ISSUE THREAD

**Issue by kevingentile** [auth0/auth0.net#574]
### Describe the problem you'd like to have solved
Looking for an abstraction of `ManagementApiClient` and its underlying clients to help in testing and extensions of this library. Currently, usages require a wrapper around the client.

### Describe the ideal solution
Include an `IManagementApiClient`, etc to be implemented by the correlating client. Similar to the existing `Auth0.IAuthenticationApiClient`

## Alternatives and current work-arounds
Wrapper interface and implementation that calls through to an instance of `ManagementApiClient`.

### Additional information, if any
N/A

**Comment by frederikprijck** [comment]
Thanks, I believe this makes perfect sense. This should be solved with https://github.com/auth0/auth0.net/pull/569

**Comment by kevingentile** [comment]
Thank you!
