### ISSUE TITLE
V2 API Issue: Inconsistent object property naming

### ISSUE THREAD

**Issue by advancedrei** [auth0/auth0.net#58]
I'm creating this issue to track Auth0's exposed API members that do not appear to adhere to the naming convention of property names in all lowercase with a space separating words.

**V2 API:**
- user.identity.isSocial

**Rules API:**
- user.clientID
- context.clientID
- context.clientName
- context.connectionStrategy
- context.samlConfiguration
- context.jwtConfiguration
- context.stats.loginsCount
- context.request.userAgent
- context.request.geoip

I will edit this list with more items as I find them. I believe the desired result would be to modify these objects to confirm to internal conventions. If v2 is "official", then it may be best to wait for v3.

**Comment by jerriep** [comment]
Another inconsistency I noticed was the IDs. Sometimes it will be <object>ID, (e.g. ClientID), other times it will just be ID.

Not sure how much they can do about this now though. It will be breaking changes.

**Comment by jerriep** [comment]
@ntotten This is more related to the actual API than it is to the .NET SDK. Not sure how you want to handle this as any change made to this now will be a breaking change.

@advancedrei What is the Rules API? Can you point me to some docs? Is this something which should be included in the .NET SDK?

**Comment by jerriep** [comment]
@ntotten Any feedback on this? I do not believe this belongs here as it is related to the underlying API.

Should we communicate this through to the API team?

Any fixes though will mean breaking changes...

**Comment by jerriep** [comment]
No feedback received. Please reopen if this is still an issue.
