### ISSUE TITLE
OrganizationCreateRequest model doesn't contain definition of  enable connections

### ISSUE THREAD

**Issue by ssurowiec** [auth0/auth0.net#584]
### Describe the problem
I want to create organization and enable connection in one request. In API Documentation is available to create , but `OrganizationCreateRequest` model doesn't have

### What was the expected behavior?
Expect to contain any property to be able to define enable connections for organization

### Environment

- **7.17.1**
- **.NET 6**

**Comment by frederikprijck** [comment]
Looks like that field is indeed missing. Would you be interested in creating a PR? I would be happy to review and merge it.
