### ISSUE TITLE
Support "Get job error details"

### ISSUE THREAD

**Issue by sleekflowleochoi** [auth0/auth0.net#590]
### Describe the problem you'd like to have solved

Lacking an API for "Get job error details".
https://auth0.com/docs/api/management/v2#!/Jobs/get_errors

**Comment by frederikprijck** [comment]
Thanks. Can't prioritise this currently, but happy to review and merge a PR if you can provide one.

**Comment by frederikprijck** [comment]
I looked into this and this is an endpoint we can not support at the current moment. It looks like the endpoint can return totally different response depending on the type of job, making it pretty weird to implement.

I have raised this internally, but for now I would recommend you to call this yourself manually.
Closing this as we can't implement an API that behaves like that.
