### ISSUE TITLE
Missing revoke token endpoint implementaion for authentication api

### ISSUE THREAD

**Issue by msmolka** [auth0/auth0.net#616]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

There is authentication api endpoint
https://auth0.com/docs/api/authentication#revoke-refresh-token

And there is no related api implementation

### Describe the ideal solution

All API endpoints has their implementation in api clients

**Comment by msmolka** [comment]
@frederikprijck : added PR  #617

**Comment by frederikprijck** [comment]
Thanks for the PR. I will see to cut a release later today.
