### ISSUE TITLE
Configure build and deployment of Release versions

### ISSUE THREAD

**Issue by jerriep** [auth0/auth0.net#62]
CI is set up on AppVeyor to create CI builds and publish Nuget packages to AppVeyor hosted feed. This needs to be expanded for release versions to publish to the official Nuget feed.

Some thoughts:
1. Should this be handled on different branches? Probably...
2. Do we really want to publish automatically to Nuget? One thing that comes to mind is that the project consists of 3 packages, Core, Auth API and Management API. If we publish automatically it means that we will always publish all 3 packages, regardless of whether that particular package has actually changed...

**Comment by advancedrei** [comment]
IMHO, I don't think you should publish automatically to NuGet. Publishing to internal feeds and/or pre-release builds is one thing, but you want to have a human gating releases to the public.

**Comment by jerriep** [comment]
Look into using AppVeyor "Deploy on Tag" feature:
https://www.appveyor.com/docs/deployment#deploy-on-tag-github-only

This way we can control deployment by tagging a release

**Comment by jerriep** [comment]
http://daveaglick.com/posts/deploying-a-public-nuget-package-from-scratch

**Comment by jerriep** [comment]
http://www.codeproject.com/Tips/806257/Automating-NuGet-Package-Creation-using-AppVeyor

**Comment by jerriep** [comment]
Custom build script with MSBuild and Nuget
http://docs.myget.org/docs/reference/custom-build-scripts

**Comment by jerriep** [comment]
Or use FAKE
http://fsharp.github.io/FAKE/
