### ISSUE TITLE
EmailVerificationTicketRequest is missing ClientId parameter

### ISSUE THREAD

**Issue by bellascalzi1** [auth0/auth0.net#628]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

As seen in this previous issue for the `PasswordChangeTicketRequest`: https://github.com/auth0/auth0.net/issues/463, the documentation for the "Create an email verification ticket" Management API [endpoint](https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification) supports adding a "ClientId" parameter, but it is not possible to add this currently using the SDK. It would be great if this could be added, as it would allow the correct app name to be displayed in the button that redirects the user when the email verification link that is generated is clicked. Currently the app name defaults to "All Applications", as can be seen in the screenshot I've put in the "Additional Context" section.

As an aside, if the fix for this is as simple as creating a PR like this: https://github.com/auth0/auth0.net/pull/464, I would be more than happy to do this myself. Let me know if this is something you guys would like me to do.

### Describe the ideal solution

The user is able to specify the ClientId in the `EmailVerificationTicketRequest`

### Alternatives and current workarounds

As a workaround what I think I will do is configure some custom text for that page via the dashboard.

### Additional context

Screenshot of email verification complete page displaying "All Applications".
![email-verification-ticket-clientid](https://github.com/auth0/auth0.net/assets/16617321/ebc66ecf-5d9f-4f0b-ac56-e8d57dae403e)

**Comment by frederikprijck** [comment]
Thanks for reporting this!

The fix should be the same as #464, yes. Happy to review a PR if you want to provide one!
