### ISSUE TITLE
Organization Update: Add Name

### ISSUE THREAD

**Issue by amummaprojectmanager** [auth0/auth0.net#638]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Would it be possible to add the name to the OrganizationUpdateRequest model? Looking at the docs, it looks like it's something that's able to be updated. 

https://auth0.com/docs/api/management/v2/organizations/patch-organizations-by-id

### Describe the ideal solution

Seems fairly simple to add it to the model with the proper documentation; Is this repo open to contributions?

### Alternatives and current workarounds

We're currently using the Auth0 library, but I can probably just write a raw HTTP request for my purposes

**Comment by frederikprijck** [comment]
Thanks, merged it!_
