### ISSUE TITLE
Management client missing cross-origin settings for client creation

### ISSUE THREAD

**Issue by laurencee** [auth0/auth0.net#641]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm using 7.22.1 from nuget.

The [API documentation for client creation](https://manage.woolworths-dev.auth0app.com/docs/api/management/v2#!/Clients/post_clients) `/api/v2/clients` has options to set `cross_origin_authentication` which is missing from this .NET client.

### Describe the ideal solution

Match the exposed v2 API contracts.

### Alternatives and current workarounds

Don't use this .NET client and call the HTTP endpoints myself manually.

**Comment by frederikprijck** [comment]
Thanks for reporting, I opened a PR to fix this.
