### ISSUE TITLE
disable_signup not set when using SDK

### ISSUE THREAD

**Issue by Cyamanide** [auth0/auth0.net#642]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the SDK I am unable to set the `disable_signup` option on my connection.

In the dashboard the `disable_signup` value is clearly sent in as part of the payload to the management API directly:

request: 
![image](https://github.com/auth0/auth0.net/assets/4545960/9bd7f158-820c-40fa-8854-50a345f6a0d7)

payload:
![image](https://github.com/auth0/auth0.net/assets/4545960/72aea028-2eaf-4c74-82f0-6f6b4a0ed0f6)

### Reproduction

1. Send request to custom API that uses Auth0 SDK:  
![image](https://github.com/auth0/auth0.net/assets/4545960/c7766c2e-5d21-4903-906c-14f987947c14)

2. Map request to ConnectionCreateRequest: 
![image](https://github.com/auth0/auth0.net/assets/4545960/e4d8043a-b05a-4bb1-96d1-7fd260a73117)

3. See successful response excluding `disable_signup`: 
![image](https://github.com/auth0/auth0.net/assets/4545960/62606d7f-1ade-42bb-b2a0-c9b7881afdfa)

4. Confirm in Auth0 Dashboard that `Disable Sign Ups` is not set: 
![image](https://github.com/auth0/auth0.net/assets/4545960/ebce7b1c-2dd4-4ce9-82c6-0993f8397d50)

### Additional context

Project dependencies: 
![image](https://github.com/auth0/auth0.net/assets/4545960/f84d30a6-8d47-4733-b19d-d1f74caa6e85)

Project .Net version: 
![image](https://github.com/auth0/auth0.net/assets/4545960/16c8e90b-fd61-4fad-9c36-581e857b80a2)

### auth0.net version

7.22.0

### .NET version

6

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Im not sure i understand why the payload you share includes properties in the Options that aren't set in the snippet you shared (e.g. `mfa`, but there are more).

Thanks.

**Comment by Cyamanide** [comment]
I show the request object being sent via the sdk in point: `2. Map request to ConnectionCreateRequest`. 
In the screenshot the `Options` property has the value `{"disable_signup":true}`.

**Comment by frederikprijck** [comment]
In the screenshot, the relevant code isnt visible due to the pop-up. I just want to ensure i get the full picture here to understand.

Also, can you verify it's not sent using corresponding tools like fiddler?

**Comment by frederikprijck** [comment]
In the screenshot, the relevant code isnt visible due to the pop-up. I just want to ensure i get the full picture here to understand.

Also, can you verify it's not sent using corresponding tools like fiddler?

**Comment by Cyamanide** [comment]
For sure, here is the code block:
![image](https://github.com/auth0/auth0.net/assets/4545960/ab8f12fb-52a1-4a04-bfbc-6e86773490f4)

And no, I am unable to capture the request to Auth0. I see my postman request and it's response but Fiddler doesn't capture the request to Auth0:

![image](https://github.com/auth0/auth0.net/assets/4545960/d364d8b6-3f04-42fc-a289-4db42e6fdcd3)

**Comment by frederikprijck** [comment]
I have looked into this and was unable to reproduce.

I tried the following:

```
var newConnectionRequest = new ConnectionCreateRequest
{
    Name = "NoSignups",
    Strategy = "auth0",
    DisplayName = "NoSignups",
    Realms = new[] { name },
    Options = new
    {
        disable_signup = true
    }
};
var newConnectionResponse = await managementClient.Connections.CreateAsync(newConnectionRequest);
```

This results in the signups to be correctly disabled:

![image](https://github.com/auth0/auth0.net/assets/2146903/2b4a59b7-8328-4c79-a05d-26b4ec4b28e7)

Next, I tried the following:

```
var newConnectionRequest = new ConnectionCreateRequest
{
    Name = "Signups",
    Strategy = "auth0",
    DisplayName = "NoSignups",
    Realms = new[] { name },
    Options = new
    {
        disable_signup = false
    }
};
var newConnectionResponse = await managementClient.Connections.CreateAsync(newConnectionRequest);
```

The results in the signups not to be disabled:

![image](https://github.com/auth0/auth0.net/assets/2146903/f5f98861-637f-4c2c-b87a-ceea7df19cac)

I would recommend debugging this on your side by explicitly setting the values like above. Then you can start and look into what is going wrong, but it might be on your application's JSON serialization side.
