### ISSUE TITLE
Retrieve User.AppMetadata as specific type instead of dynamic

### ISSUE THREAD

**Issue by MichaelPruefer** [auth0/auth0.net#645]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm always frustrated when... (interesting placeholder...)

i try to read Auth0.ManagementApi.Models.UserBase.AppMetadata as it's type is dynamic.
I can only see what the real type is when debugging.

And then i have to cast to a type which i can't control and could be changed at any time (for now it's a Newtonsoft.Json.Linq.JObject).

### Describe the ideal solution

I'd like to have a method get the AppMetadata converted into my own type. e.g.

`user.GetAppMetadata<MyAppMetadataType>()`

So the Auth0 implementation can convert AppMetadata possibly via Newtonsoft.Json.Linq.JObject.ToObject<T> into my desired type without me knowing how AppMetadata was de-/serialized along the way.

### Alternatives and current workarounds

Currently i have to check which type AppMetadata is via e.g. `if (user.AppMetadata is Newtonsoft.Json.Linq.JObject metadataObject) ... ` and then use a cast

### Additional context

The same principle should be applied to `user.UserMetadata`

**Comment by frederikprijck** [comment]
Thanks for reaching out. AppMetadata and UserMetadata are both dynamic because they are in fact dynamic.

You should be able to convert the JObject to your own type pretty easily in your own code.

```cs
public class MyUserMetadata
{
    public string Color { get; set; }
}

public static class UserExtensions
{
    public static MyUserMetadata GetUserMetadata(this User user)
    {
        return (user.UserMetadata as JObject).ToObject<MyUserMetadata>();
    }
}
```

The above allows you to call `GetUserMetdata()` on our User class and have it return your own type. This avoids having to work with dynamics or JObjects through the rest of your code.

You can do the same for AppMetdata.

Closing, as this can be solved in user-land with minimal code and doesn't require changes to our SDK.

**Comment by MichaelPruefer** [comment]
I concur, they are not dynamic.
In fact in Auth0 i can only add JSON, so in AppMetadata should be a JSON structure of some kind.
But as the Type is dynamic i don't know which current type it is.
For now it is a Newtonsoft.Json.Linq.JObject but if you somehow decide to switch to JSON.net or anything else my code breaks at runtime because i relied on AppMetadata being Newtonsoft.Json.Linq.JObject.

If you would provide the .ToObject<T> method on the User class i don't need to know which json implementation you use and can rely that i get my T-instance no matter what.

**Comment by frederikprijck** [comment]
I am happy to review a PR to implement both GetUserMetadata and GetAppMetadata that does the JSON parsing.
