### ISSUE TITLE
expose external_id on Auth0.ManagementApi.Models.Job

### ISSUE THREAD

**Issue by gwrobbiekouwenberg** [auth0/auth0.net#653]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The current Job entity does not expose external_id while you can retrieve it via direct Rest call to the API.

### Describe the ideal solution

Add external_id to the Job entity

### Alternatives and current workarounds

I can currently use a direct Rest call using HttpClient but this seems like a workaround when this SDK exists.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

I can't see any external_id being mentioned on [the documentation for the corresponding API endpoint](https://auth0.com/docs/api/management/v2/jobs/get-jobs-by-id), assuming you are talking about the endpoint to retrieve a job.

Can you elaborate the endpoint you are talking about and refer to the correspondig documentation so I can see what you mean?

**Comment by gwrobbiekouwenberg** [comment]
Thanks for the quick response.

I am using the `Auth0.ManagementApi` v7.22.3 NuGet package to call the `Auth0.ManagementApi.Clients.IJobsClient` `GetAsync` method to retrieve the status of a job. (through a IManagementApiClient)
see: 

Docs I used:
- api: https://auth0.github.io/auth0.net/api/Auth0.ManagementApi.Clients.IJobsClient.html#Auth0_ManagementApi_Clients_IJobsClient_GetAsync_System_String_System_Threading_CancellationToken_
- Job model: https://auth0.github.io/auth0.net/api/Auth0.ManagementApi.Models.Job.html

I can use the following rest api to get the same data: 
https://auth0.com/docs/api/management/v2/jobs/get-jobs-by-id
The documentation does not seem to reflect the actual data being returned by the api.

given a valid job id i can get the following response.

``` json
{
  "type": "users_import",
  "status": "completed",
  "connection_id": "con_redacted",
  "external_id": "96acfb71-a182-4d7f-8010-75cf6364385b",
  "summary": {
    "failed": 0,
    "updated": 1000,
    "inserted": 0,
    "total": 1000
  },
  "connection": "Username-Password-Authentication",
  "created_at": "2023-09-06T12:23:28.899Z",
  "id": "job_CLn76OPRAah1GXwA"
}
```

**Comment by gwrobbiekouwenberg** [comment]
This field can be used by a consumer of the auth0 api when starting a job like the upload_users job to tag a job with a id value. like linking it to some background process on consumer side

Met vriendelijke groet,
ROBBIE
INN IT TOGETHER
***@***.***
AZURE READINESS ASSESSMENT
Sneller innoveren en vooral veiliger werken? Inzicht in wat een Azure 
​migratie ​betekent en kost voor jouw organisatie?
________________________________

**Comment by frederikprijck** [comment]
@benrorije fixed in https://github.com/auth0/auth0.net/pull/679

**Comment by benrorije** [comment]
That is quick, thanks! :-)
