### ISSUE TITLE
Expose is_domain_connection on Connection

### ISSUE THREAD

**Issue by amummaprojectmanager** [auth0/auth0.net#655]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

is_domain_connection is an option but it doesn't seem to exist on ConnectionUpdateRequest which just inherits ConnectionBase

<img width="449" alt="image" src="https://github.com/auth0/auth0.net/assets/114442315/801805c0-272a-497d-8a59-0eb6eae5366d">

### Describe the ideal solution

Add the property - I'll raise a PR shortly after double checking this one

**Comment by frederikprijck** [comment]
Thanks for the PR!
