### ISSUE TITLE
Please add methods PutAppMetadata<T> and PutUserMetadata<T> for User to function as a merge

### ISSUE THREAD

**Issue by mharrisn** [auth0/auth0.net#705]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

It appears that if you call the existing methods SetAppMetadata<T> or SetUserMetadata<T>, they replace the entire JSON representation of `app_metadata` and `user_metadata` respectively. Given the dynamic nature of these spaces, it would be ideal to have the ability to only set the portion of the object that your use case is concerned with. This would avoid the risk of inadvertently overwriting JSON that another application/team requires without a lot of JSON manipulation code - plus we keep the benefits of type safety. 

### Describe the ideal solution

Assuming I have classes like this:
```c#
public class AcmeAppMetadata {
    public MyGreatFeatureSettings MyGreatFeatureSettings {get; set;}
}
public class MyGreatFeatureSettings {
    public int? NumberOfTimesIveBeenCalledAwesome {get; set;}
}
```
So if we want to update the app metadata for only the `myGreatFeatureSettings` child object of the metadata object,  we could use something like a Put:
```c#
// Get the slice of metadata we care about
var userData = myUser.GetAppMetadata<AcmeAppMetadata>();
userData.MyGreatFeatureSettings.NumberOfTimesIveBeenCalledAwesome = 1000;

// Set only the slice of metadata that we care about - without impacting any other JSON nodes
myUser.PutAppMetadata<AcmeAppMetadata>(userData);
```

### Alternatives and current workarounds

Calling SetAppMetadata<T> blows out the entire JSON Object with only what's defined in the current object being applied. This is problematic for larger teams where there may be different use cases that need to be covered. An option to Put/Merge the object would be fantastic.

To avoid potentially overwriting nodes that other teams may need, I have to write a bunch of JSON traversing code to modify AppMetadata in dotnet. This feature would make it trivial to modify the portions of the JSON that are a concern for our use case without impacting other teams.

**Comment by frederikprijck** [comment]
Thanks for reaching out. I am not sure I understand what you are asking.

> Given the dynamic nature of these spaces, it would be ideal to have the ability to only set the portion of the object that your use case is concerned with. This would avoid the risk of inadvertently overwriting JSON that another application/team requires without a lot of JSON manipulation code - plus we keep the benefits of type safety.

Put is about replacing the entire object, so I do not see how it would help in the above scenario.

Can you elaborate how the following:

```cs
// Get the slice of metadata we care about
var userData = myUser.GetAppMetadata<AcmeAppMetadata>();
userData.MyGreatFeatureSettings.NumberOfTimesIveBeenCalledAwesome = 1000;

// Set only the slice of metadata that we care about - without impacting any other JSON nodes
myUser.PutAppMetadata<AcmeAppMetadata>(userData);
```
would differ from what we currently have:

```cs
// Get the slice of metadata we care about
var userData = myUser.GetAppMetadata<AcmeAppMetadata>();
userData.MyGreatFeatureSettings.NumberOfTimesIveBeenCalledAwesome = 1000;

// Set only the slice of metadata that we care about - without impacting any other JSON nodes
myUser.SetAppMetadata<AcmeAppMetadata>(userData);
```

I just don't see the difference. I have a feeling you are refering to `patch` rather than `put`. However, that is not something the user class should be concerned about and something you need to write your self. Alof of classes in any kind of SDK expose getter/setters, if you want to only partially set something you'll need to work around that as well, so I am not sure I can see the difference here.

**Comment by frederikprijck** [comment]
Thanks for getting back with that information.

I do have to admit that I do not think this should be part of the User class in our SDK. We provide a .NET library around the Auth0 Management API. The API accepts a user_metadata/app_metadata object, and it overrides whatever is already on the server with what you send along. Our SDK represents that behavior.

If you need additional logic to the layer we provide on top of the API, nothing stops you from doing that in your own code, which you can still distribute across the different teams you are talking about.

Closing this for now, as I believe this isn't something we want to add currently.

**Comment by reinux** [comment]
I'm a little confused. The Management API does indeed have a [PATCH method](https://auth0.com/docs/api/management/v2/users/patch-users-by-id) for exactly this use case. It allows you to update individual fields within the metadata.
