### ISSUE TITLE
Actions object missing installed integration data

### ISSUE THREAD

**Issue by robertmclaws** [auth0/auth0.net#710]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The Actions API objects are missing data about installed integrations.

The following data is not captured by the de-serialized .NET objects:

```json
      "installed_integration_id": "a758bb11-51fd-4e81-b707-e41f565fd046",
      "integration": {
        "id": "750ce7ba-eac5-44a2-97ac-a67b2183bdea",
        "catalog_id": "auth0-country-based-access",
        "url_slug": "country-based-access",
        "partner_id": "d929f92d-efd5-465f-9801-cdd40bfe2c39",
        "name": "Country-based Access",
        "description": "This integration allows you to restrict access to your applications by country. You may choose to implement Country-based Access controls for various reasons, including to allow your applications to comply with unique restrictions based on where you do business. \n\nWith the Country-based Access integration, you can define any and all countries to restrict persons and entities from those countries logging into your applications. ",
        "short_description": "Restrict access to users by country",
        "logo": "https://cdn.auth0.com/marketplace/catalog/content/assets/creators/auth0/auth0-avatar.png",
        "terms_of_use_url": "https://cdn.auth0.com/website/legal/files/mktplace/auth0-integration.pdf",
        "public_support_link": "https://support.auth0.com/",
        "updated_at": "2022-05-18T22:38:09.809749669Z",
        "created_at": "2022-05-12T19:54:02.958669136Z",
        "feature_type": "action",
        "current_release": {
          "id": "",
          "semver": {}
        }
      },
```

I'm writing code to automate the installation and configuration of Actions in .NET, and I need this information to be able to complete the features I'm working on.

### Reproduction

1. Start up Fiddler
2. Make a request to the Actions API: `ManagementApiClient.Actions.GetAllAsync(new GetActionsRequest(), new PaginationInfo(), cancellationToken)`
3. Loop through the resulting object list in the debugger
4. See that the .NET object does not contain information about installed integrations, but the returned payload does.

### auth0.net version

7.26.1

### .NET version

8.0.4

**Comment by kailash-b** [comment]
This is be available from `v7.29.0` onwards
