### ISSUE TITLE
Add ability to install Marketplace integrations from the API

### ISSUE THREAD

**Issue by robertmclaws** [auth0/auth0.net#711]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The Actions API returns installed integrations. But it does not allow an integration to be installed programatically.

### Describe the ideal solution

I would like to request the ability to install & upgrade Marketplace integrations by either the UID or the catalog ID so that I can automatically configure these integrations on customer tenants.

### Alternatives and current workarounds

The only workaround right now is to do it manually on the website.

### Additional context

I am building integrations for an app management platform and would like to be able to manage what is installed automatically for the end user using the Management API. Thanks!

**Comment by frederikprijck** [comment]
We can not support features in the SDK that are not supported from the Management APi itself. I recommend opening feedback [here](https://auth0.com/feedback). If this end up being added, it should also end up in our SDK.
