### ISSUE TITLE
IPagedList<T>.Paging null on on .Users.GetAllAsync

### ISSUE THREAD

**Issue by christophwille** [auth0/auth0.net#722]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Paging results from .Users.GetAllAsync doesn't work because I do not get `PagingInformation Paging` on `IPagedList`.

### Reproduction

```
            var request = new GetUsersRequest
            {
                Query = $"email:*",
                SearchEngine = "v3"
            };

            var page = 0;
            var perPage = 1;

            var queryResult = await managementApiClient.Users.GetAllAsync(request,
                    new Auth0.ManagementApi.Paging.PaginationInfo(page, perPage),
                    cancellationToken);
```

I properly get exactly one item, however, queryResult.Paging is null (also for v2)

### auth0.net version

7.26.2

### .NET version

8.0

**Comment by kailash-b** [comment]
Thanks for reaching out @christophwille 
The `Paging` property in the response gets populated only when the [PaginationInfo](https://auth0.github.io/auth0.net/api/Auth0.ManagementApi.Paging.PaginationInfo.html) in the request has `includeTotals`  as `true`.

Can you try passing `includeTotals` as `true` like below? 

```
            var request = new GetUsersRequest
            {
                Query = $"email:*",
                SearchEngine = "v3"
            };

            var page = 0;
            var perPage = 1;

            var queryResult = await managementApiClient.Users.GetAllAsync(request,
                    new Auth0.ManagementApi.Paging.PaginationInfo(page, perPage, true),
                    cancellationToken);
```

**Comment by christophwille** [comment]
That indeed works. May I suggest that

```
//   includeTotals:
//     Whether to return the complete total result count (true) or not (false).
```

comment on PaginationInfo class is misleading? https://auth0.com/docs/manage-users/user-search/view-search-results-by-page is a bit better, but still "include_totals | Set to true to include a query summary as part of the result." doesn't indicate that is the information for paging.

**Comment by kailash-b** [comment]
Yes agreed. 
We will update the documentation to explain it better. 
Thanks! 
We are closing this issue now. Please reach out in case there's anything else.
