### ISSUE TITLE
OrganizationCreateInvitationRequest documentation reports that SendInvitationEmail defaults to true ,

### ISSUE THREAD

**Issue by ardove** [auth0/auth0.net#727]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While testing an (enterprise) integration, I've found that the Auth0 ManagementApi SDK does NOT set the "SendInvitationEmail" parameter to true (even though the documentation says it defaults to true. 

This aligns with what the rest api documentation says, but no emails are sent unless you actually set the invitaiton email to true. 
![{3FAA1E5F-830B-41A7-B973-F40A0627A3B3}](https://github.com/user-attachments/assets/01075ea1-f25c-4a29-b886-ec1ab597d02a)

### Reproduction

1. Invoke the client.Organizations.CreateInvitationAsync method with valid parameters.

```
OrganizationInvitation inviteResponse = await client.Organizations.CreateInvitationAsync(
    orgId,
    new OrganizationCreateInvitationRequest
    {
        ClientId = auth0ApplicationClientId,
        ConnectionId = _connectionId,
        Invitee = new OrganizationInvitationInvitee
        {
            Email = userEmail
        },
        Inviter = new OrganizationInvitationInviter
        {
            // this seems to only be for displaying in the auth0 dashboard
            Name = inviterName
        },
        // SendInvitationEmail = true
    });
```

### auth0.net version

7.25.0

### .NET version

4.8

**Comment by kailash-b** [comment]
This is fixed in the latest available version `7.27.0`
Closing the issue now.
