### ISSUE TITLE
Support Nullable Reference Types

### ISSUE THREAD

**Issue by voroninp** [auth0/auth0.net#750]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like the library to support NRTs for better semantics.

### Describe the ideal solution

```
public string Next { get; set; } = null;
```

`Next` should be of type `string?` to convey that there are cases (end of result) when `Next` is `null`.

**Comment by kailash-b** [comment]
Hi @voroninp 
Thanks for reaching out.

While we agree that NRTs provide better semantics and convey more information, we will not be able to support these at the moment. 
We currently are targeting `netstandard2.0` and `net462` versions which have `C# 7.x` as the language version. 
NRTs are supported from `C# 8.0` and above. 

Since our target versions do not natively support `C# 8.0+`, we will not be able to make this change right now.

**Comment by voroninp** [comment]
In theory you could use a package like Polysharp and target the latest version of the compiler. Of course you won't be able to use features which depend on run-time advances, but NRTs are implemented via attributes.

**Comment by kailash-b** [comment]
yes that could be possible. It might need a thorough testing on our end to ensure nothing breaks (it ideally shouldn't break anything)
We will add this as a backlog item on our radar.

**Comment by kailash-b** [comment]
We have added a ticket internally to analyse the possibility of using PolySharp in our code and referenced this issue. 
Thanks for reaching out. Closing this issue for now.
