### ISSUE TITLE
Missing fields when creating users

### ISSUE THREAD

**Issue by jamestoyer** [auth0/auth0.net#77]
I've been looking through the code for creating users, and I've noticed an inconsistency with how you can create users on API v2 and the client library. The API supports adding a `given_name`, `family_name`, and `name`, but the Users client doesn't.

I'm aware the first three are on the API documentation, but they are allowable when using the API explorer. Is this something that's going to disappear off the API, hence it's exclusion from the users client?

**Comment by jerriep** [comment]
@jamestoyer It is possible that it was just overlooked by me.

Can you please send me more details regarding the endpoint (URL) on the API you are calling, as well as the payload (JSON) you are sending? I can then correlate this with the .NET client library and make adjustments as required.

**Comment by jamestoyer** [comment]
Sure. I've used the payload on the endpoint below to create a user. This was done using the API explorer. 

Endpoint: `POST /api/v2/users`
Payload:
```
{
  "connection": "Initial-Connection",
  "email": "john.doe@gmail.com",
  "username": "johndoe",
  "password": "secret",
  "user_metadata": {},
  "email_verified": false,
  "app_metadata": {}, 
  "given_name": "John",
  "family_name": "Doe",
  "name": "John Doe",
  "nickname": "Jonny D"
}
```

As you'll notice, I've also gone ahead and checked that you could set the `nickname` property too.

Something else I noticed when using the API explorer is that if you don't require a username in the connection you're creating a user on, you shouldn't send the `username` property. If you do the API will give you an exception back. Now I've not checked doing this with the management API client, but a quick glance at the code suggests that you always send the `username` property when creating a user.

I plan to start reimplementing an existing project against v2 of the API today, so I can give more feedback then on the `username` issue.

**Comment by jerriep** [comment]
This is an oversight on my part.

I will fix this as part of #57

**Comment by jamestoyer** [comment]
Everything works fine when creating a user on connection when a username isn't required. I now see your tests cover this scenario.

I've had to halt my re-integration however as the `blocked` field is missing on the core user. Would you like me to open a new issue about that or will it be wrapped up in #57?

**Comment by jerriep** [comment]
@jamestoyer Thanks for reporting this

I have created #82

It is available when updating a user, but not when reading the user, so I will add it to the structure when returning a user from the API - either a single user or a list of users. 

According to the API documentation this is the only 2 scenarios when this field should be available. 

Will this solve your issue, is there another scenario when you expect the `blocked` field to be available?

**Comment by jamestoyer** [comment]
@jerriep Thanks. This would solve my issue. 

I can't think of any other scenarios where I would need it

**Comment by jerriep** [comment]
@jamestoyer regarding the username; if the property is null it will not be serialized and therefor not sent in the JSON I send the the API. Does this resolve your concern regarding that?

**Comment by jerriep** [comment]
@jamestoyer Also, the `family_name`, `given_name` and `name` properties are already available at the moment when returning a user. The names of the properties are however different; they are `LastName`, `FirstName` and `Fullname` respectively.

It is confusing, I know, but changing it now will result in a breaking change which I do not want to do.

I am moving these properties to the `UserBase` class so they are available when creating or updating a user as well.

**Comment by jamestoyer** [comment]
Awesome, thank you.

I also prefer `FirstName`, `LastName` and `FullName`. In my opinion they make more sense than `given_name`, `family_name` and `name`.
