### ISSUE TITLE
Header and footer on docs

### ISSUE THREAD

**Issue by jerriep** [auth0/auth0.net#84]
Header:
https://github.com/auth0/web-header

Footer should be the same as on https://auth0.com/docs

Style guide:
https://styleguide.auth0.com/

**Comment by jerriep** [comment]
@ntotten Who would be able to assist me with getting the header working? 

I have included the JS from the CDN, as well as the JS code in the sample on the web-header website, but I get a JS error about "require not defined". Please see screenshot below...

![image](https://cloud.githubusercontent.com/assets/1006420/12264605/9ea965a8-b940-11e5-9da5-d002c2cdebce.png)

**Comment by ntotten** [comment]
@cristiandouce what's up with this? Require doesnt seem like it should be in the browser script.

**Comment by jerriep** [comment]
As per Cristian on Slack:

you cant use standalone + require... standalone simply adds a window.Alias thing so it doesn't colide with whatever require.js or common.js `require` function you may have...
to fix, simply replace this

```
var WebHeader = require('web-header');
```
for this

```
var WebHeader = window.WebHeader;
```

**Comment by jerriep** [comment]
Not relevant anymore. Docs runs as completely separate website
