### ISSUE TITLE
Breadcrumbs on docs should be changed

### ISSUE THREAD

**Issue by ntotten** [auth0/auth0.net#86]
The breadcumbs should be rooted with Documentation.

Documentation > Auth0.net SDK > then subpages

Documenation should point to `/docs` the Auth0.NET SDK should point to the relative root of the generated site

**Comment by jerriep** [comment]
@ntotten I am closing this as the .NET SDK docs now run as a completely separate website and not in the context of the main docs website. So I believe this is not relevant anymore.

Please feel free to reopen if you think it is still relevant
