### ISSUE TITLE
Support the "scope" option when calling /delegation.

### ISSUE THREAD

**Issue by nicosabena** [auth0/auth0.net#9]
The /delegation api (https://docs.auth0.com/auth-api#post--delegation) supports the "scope" option to indicate the type of id token you are looking for.
Right now the GetDelegationToken() method in the API is not giving any way of providing this option.
```C#
        /// <summary>
        /// Gets a delegation token.
        /// </summary>
        /// <param name="token">The current access token.</param>
        /// <param name="targetClientId">The client id of the target application.</param>
        /// <returns>An instance of DelegationTokenResult containing the delegation token id.</returns>
        public DelegationTokenResult GetDelegationToken(string token, string targetClientId)
```

**Comment by jimlambrt-roadscholar** [comment]
Just a comment: supporting scope as a parameter is extremely important.  We load authorization claims into the app_metadata for each user.   Without app_metadata in the scope, we would have to go back to auth0 endpoints during authen/auth and add more than 1.5 secs to every request.

**Comment by jerriep** [comment]
Scope supported since V2 of new .NET SDK.
